Repository harness/harness-core, pull requests merged in 2022-08, with the labels that each got.

#36110 fix: [CI-5183]: count bitbucket users correctly
  332-ci-manager/service/src/main/java/io/harness/ci/core/trigger/WebhookTriggerProcessorUtils.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/WebhookTriggerProcessorUtils.java
  product/ci/scm/converter/common.go
  product/ci/scm/proto/scm.proto
Labels: gojava

#34050 [feat]: [CCM-7875]: Add CCM related resources, roles and permissions
  340-ce-nextgen/config.yml
  340-ce-nextgen/src/main/java/io/harness/ccm/CENextGenConfiguration.java
  340-ce-nextgen/src/main/java/io/harness/ccm/CENextGenModule.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/AnomalyResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/BudgetResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/BusinessMappingResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveFolderResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/recommendation/RESTWrapperRecommendationOverview.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/BusinessMappingResourceTest.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/PerspectiveFolderResourceTest.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/PerspectiveResourceTest.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/recommendation/RESTWrapperRecommendationOverviewTest.java
  340-ce-nextgen/src/test/resources/test-config.yml
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/core/overview/CCMMetaDataService.java
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/dto/overview/CCMMetaData.java
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/query/budget/BudgetsQuery.java
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/query/perspectives/PerspectivesQuery.java
  490-ce-commons/BUILD.bazel
  490-ce-commons/src/main/java/io/harness/ccm/rbac/CCMRbacHelper.java
  490-ce-commons/src/main/java/io/harness/ccm/rbac/CCMRbacHelperImpl.java
  490-ce-commons/src/main/java/io/harness/ccm/rbac/CCMRbacPermissions.java
  490-ce-commons/src/main/java/io/harness/ccm/rbac/CCMResources.java
  access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
  access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
  access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
  dockerization/ce-nextgen/scripts/replace_configs.sh
Labels: do-not-merge

#36228 feat: [CI-5187]: Enable split test to call TI service directly for VMs
  product/ci/common/external/util.go
  product/ci/split_tests/ti/BUILD.bazel
  product/ci/split_tests/ti/ti_helper.go
Labels: go

#36216 feat: [BT-1605] identify flaky unit tests
  bazelrc.remote
  tools/bazel/GenTestRules.bzl
Labels: java

#36365 feat: [CI-5075]: LE and Addon changes for background step
  product/ci/addon/grpc/handler.go
  product/ci/addon/tasks/run.go
  product/ci/addon/tasks/run_test.go
  product/ci/engine/new/executor/step_executor.go
  product/ci/engine/new/executor/step_executor_test.go
Labels: go
