Repository harness/harness-core, pull requests merged in 2022-02, with the labels that each got.

#30451 [fix]: [CI-3368]: Upgrade Go library to version 1.17.5
  WORKSPACE
Labels: gojava

#30470 [fix]: [CI-2901]: Remove github.com/dgrijalva/jwt-go dependency
  WORKSPACE
  commons/go/lib/go.sum
  product/ci/addon/go.sum
  product/ci/engine/go.sum
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: gojava

#30492 [feat]: [CCM-5479]: Increase max perspective limit to 250
  450-ce-views/src/main/java/io/harness/ccm/views/service/impl/CEViewServiceImpl.java
  450-ce-views/src/test/java/io/harness/ccm/views/service/impl/CEViewServiceImplTest.java
Labels: do-not-merge

#30550 [fix]: [CI-0]: fix failing UTs
  .github/workflows/go_build.yaml
  .github/workflows/no_op_go.yaml
  product/ci/addon/grpc/handler_test.go
  product/ci/addon/tasks/plugin_test.go
Labels: go

#30721 [fix]: [CI-3384]: Support running custom Java agents with TI
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/testintelligence/java/maven.go
  product/ci/addon/testintelligence/java/maven_test.go
Labels: go

#30687 feat: [CCM-5509]: Cloud Cost Details REST APIs
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/costdetails/RESTWrapperCostDetails.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveCustomFieldResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveReportResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java
  340-ce-nextgen/src/main/java/io/harness/ccm/remote/utils/RESTToGraphQLHelper.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/PerspectiveReportResourceTest.java
  340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/PerspectiveResourceTest.java
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/dto/common/StatsInfo.java
  374-ceng-graphql/src/main/java/io/harness/ccm/graphql/dto/perspectives/CostDetailsQueryParamsDTO.java
  450-ce-views/src/main/java/io/harness/ccm/views/graphql/QLCEView.java
  450-ce-views/src/main/java/io/harness/ccm/views/graphql/QLCEViewEntityStatsDataPoint.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/entities/CCMField.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/entities/CCMOperator.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/entities/CCMStringFilter.java
Labels: do-not-merge

#30228 feat: [DEL-3136]: Cleanup yaml for delegates
  400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
  400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl
  400-rest/src/main/resources/delegatetemplates/common/secret.ftl
  400-rest/src/main/resources/delegatetemplates/common/upgrader.ftl
  400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl
  400-rest/src/main/resources/delegatetemplates/harness-delegate-ng-immutable.yaml.ftl
  400-rest/src/test/resources/expectedHarnessDelegate.yaml
  400-rest/src/test/resources/expectedHarnessDelegateImmutable.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgClusterAdmin.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgClusterAdminImmutable.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgClusterViewer.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgClusterViewerImmutable.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgNamespaceAdmin.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgNamespaceAdminImmutable.yaml
  400-rest/src/test/resources/expectedHarnessDelegateNgWithoutDescription.yaml
  400-rest/src/test/resources/expectedHarnessDelegateWithCiEnabled.yaml
  dockerization/delegate/immutable-scripts/start.sh
Labels: pinned

#30753 feat: [PL-22538]: exposed GetLatestCommitOnFile as SCM API
  260-delegate/module-dependency.hash
  270-delegate-service-app/module-dependency.hash
  product/ci/scm/file/file.go
  product/ci/scm/git/git.go
  product/ci/scm/git/git_test.go
  product/ci/scm/go.sum
  product/ci/scm/grpc/handler.go
  product/ci/scm/proto/scm.proto
Labels: gojava

#30897 [feat]: [CI-3462]: Add variable ADDITIONAL_CERTS_PATH on delegate to be used by SCM service
  260-delegate/module-dependency.hash
  270-delegate-service-app/module-dependency.hash
  952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
  960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java
  product/ci/scm/gitclient/gitclient.go
  product/ci/scm/proto/scm.proto
Labels: gojava

#30658 Fix: [CDS-2170]: Adds support for workflow variables rendering for Cloud Formation - Git
  .mailmap
  260-delegate/src/test/java/software/wings/delegatetasks/CloudFormationCommandTaskHandlerTest.java
  260-delegate/src/test/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCommandTaskHandlerTest.java
  400-rest/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java
  400-rest/src/test/java/software/wings/sm/states/provision/CloudFormationCreateStackStateTest.java
  990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
  scripts/fix-unknown-authors.py
  scripts/jenkins/author-check.sh
  scripts/jenkins/authorsList.txt
Labels: bug, good first issue
