Repository harness/harness-core, pull requests merged in 2022-11, with the labels that each got.

#39580 [fix]: [CCM-9722]: Added minCpu and minMem in node recommendation request
  490-ce-commons/src/main/java/io/harness/ccm/commons/beans/recommendation/RecommendationUtils.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/beans/recommendation/models/RecommendClusterRequest.java
Labels: do-not-merge

#39734 fix: [CI-6031]: Autodetect packages from scala files
  product/ci/addon/testintelligence/java/helper.go
Labels: go

#38730 feat: [CI-5816]: Autodetect support for Scala and Kotlin
  commons/go/lib/utils/utils.go
  commons/go/lib/utils/utils_test.go
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/helper.go
  product/ci/addon/testintelligence/java/maven.go
  product/ci/addon/testintelligence/java/sbt.go
Labels: go

#39937 fix: [CI-6079]: Fix empty test added by the test splitter
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/split_tests/utils/utils.go
Labels: go

#40016 fix: [CI-6115]: Fix callgraph avro format
  product/ci/common/avro/schema/callgraph/callgraph.go
Labels: go

#39804 [fix]: [CI-6052]: addon side, use package detect in addon
  commons/go/lib/utils/BUILD.bazel
  commons/go/lib/utils/utils.go
  commons/go/lib/utils/utils_test.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/testintelligence/java/helper.go
  product/ci/addon/testintelligence/java/helper_test.go
  product/ci/ti-service/types/types.go
Labels: go

#40233 fix: [CHAOS-797]: Make eligibleToExecuteDelegateIds() check optional in ng-manager chaos resource
  120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosServiceImpl.java
Labels: java

#40161 [feat]: [CI-5801]: Security fixes for CI-SCM service
  WORKSPACE
  product/ci/scm/docker/Dockerfile
Labels: gojava

#40541 feat: [PIE-6423]: SCM create/update File implementation using GIT commands
  WORKSPACE
  product/ci/scm/file/BUILD.bazel
  product/ci/scm/file/file.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/proto/scm.proto
Labels: gojava
