Repository harness/harness-core, pull requests merged in 2022-03, with the labels that each got.

#31109 [fix]: [CI-3532]: TI - add logging when instrumentation is disabled
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/maven.go
Labels: go

#31172 [fix]: [CI-3634]: Add nudge for certificates
  product/ci/common/external/util.go
Labels: go

#30919 fix: [CI-3371]: update package self version again
  product/ci/addon/go.mod
  product/ci/engine/go.mod
Labels: go

#31475 fix: [CI-3371]: update package common lib version again
  product/ci/scm/go.mod
Labels: go

#31507 fix: [CDS-2998]: Gitlab - branch name encoding for getLatestCommit API
  product/ci/scm/git/git.go
Labels: gojava

#31165 feat: [PL-23377]: Adding Azure support to SCM
  WORKSPACE
  product/ci/scm/README.md
  product/ci/scm/file/BUILD.bazel
  product/ci/scm/file/azure_test.go
  product/ci/scm/file/file.go
  product/ci/scm/git/BUILD.bazel
  product/ci/scm/git/azure_test.go
  product/ci/scm/gitclient/BUILD.bazel
  product/ci/scm/gitclient/gitclient.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/proto/scm.proto
Labels: go

#31599 fix: [CI-2495]: Limit length of log line to 70KB
  product/ci/common/logs/remote_writer.go
  product/ci/common/logs/remote_writer_test.go
Labels: go

#31644 [feat]: [CI-3828]: Support for Powershell in Linux Builds
  260-delegate/module-dependency.hash
  270-delegate-service-app/module-dependency.hash
  320-ci-execution/src/main/java/io/harness/ci/serializer/RunStepProtobufSerializer.java
  product/ci/addon/tasks/run.go
  product/ci/engine/proto/execution.proto
Labels: gojava

#31879 feat: [PL-23377]: Adding Azure webhook support to SCM
  WORKSPACE
  product/ci/scm/file/file_test.go
  product/ci/scm/git/git_test.go
  product/ci/scm/gitclient/gitclient.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/grpc/handler_test.go
  product/ci/scm/parser/BUILD.bazel
  product/ci/scm/parser/parser.go
  product/ci/scm/parser/parser_test.go
  product/ci/scm/parser/testdata/azure_pr.json
  product/ci/scm/parser/testdata/azure_pr.json.golden
  product/ci/scm/proto/scm.proto
  product/ci/scm/repo/BUILD.bazel
  product/ci/scm/repo/azure_test.go
  product/ci/scm/repo/repo.go
  product/ci/scm/repo/repo_test.go
Labels: go, gojava
