Repository harness/harness-core, pull requests merged in 2022-10, with the labels that each got.

#38144 [fix]:[CCM-8846]: Avoid spot instances fall under any nodepool
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/util/InstanceMetaDataUtils.java
  batch-processing/service/src/main/java/io/harness/batch/processing/writer/constants/K8sCCMConstants.java
  batch-processing/service/src/test/java/io/harness/batch/processing/tasklet/util/InstanceMetaDataUtilsTest.java
Labels: do-not-merge

#38644 fix: [CI-5806]: Fix duplicate bazel query
  product/ci/addon/testintelligence/java/bazel.go
Labels: go

#38655 fix: [CI-5806]: Add UT for duplicate bazel query fix
  product/ci/addon/testintelligence/java/bazel_test.go
Labels: go

#38608 feat: [CI-5426]: Autodetect support for Gradle
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/helper.go
Labels: go

#38986 [feat]: [PIE-5803]: Handling errors for not loading local.env file for the remote env
  .github/workflows/go_build.yaml
  WORKSPACE
  queue-service/hsqs/cmd/BUILD.bazel
  queue-service/hsqs/cmd/server.go
  queue-service/hsqs/go.mod
  queue-service/hsqs/go.sum
  queue-service/hsqs/handler/BUILD.bazel
  queue-service/hsqs/store/redis/BUILD.bazel
Labels: go

#39392 feat: [PL-29433]: fix listFilesInCommitAPI pagination issues and add corresponding SCM to delegate
  100-migrator/config.yml
  270-delegate-service-app/delegate-service-config.yml
  270-delegate-service-app/src/test/resources/test-config-delegate-service.yml
  360-cg-manager/config.yml
  960-api-services/src/main/java/io/harness/delegate/clienttools/ScmVersion.java
  960-api-services/src/test/java/io/harness/delegate/clienttools/InstallUtilsTest.java
  dockerization/delegate-proxy/setup.sh
  dockerization/delegate/scripts/client_tools.sh
  on-prem/disconnected_on_prem_pov_installer/generate.sh
  on-prem/dockerless_pov_installer_generator/generate_installer.sh
  on-prem/harness_disconnected_on_prem_pov_final/install_harness.sh
  product/ci/scm/file/file.go
Labels: gojava
