Repository harness/harness-core, pull requests merged in 2022-09, with the labels that each got.

#37130 fix: [CI-5467]: Changed go-scm version for gitlab commit date fix
  WORKSPACE
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: go

#37240 fix: [PLG-1374]: added referer to start trial
  920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java
  920-ng-signup/src/main/java/io/harness/signup/services/SignupService.java
  920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java
  920-ng-signup/src/test/java/io/harness/signup/services/SignupServiceImplTest.java
  930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java
  930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java
  930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java
  930-ng-license-manager/src/main/java/io/harness/licensing/services/LicenseService.java
  930-ng-license-manager/src/test/java/io/harness/licensing/api/resource/LicenseResourceTest.java
  930-ng-license-manager/src/test/java/io/harness/licensing/services/DefaultLicenseServiceImplTest.java
  970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java
Labels: do-not-merge

#37241 fix: [CI-5490]: Modularize split test utils
  product/ci/addon/remote/BUILD.bazel
  product/ci/addon/remote/ti.go
  product/ci/common/external/util.go
  product/ci/split_tests/BUILD.bazel
  product/ci/split_tests/main.go
  product/ci/split_tests/main_test.go
  product/ci/split_tests/ti/BUILD.bazel
  product/ci/split_tests/ti/ti_helper.go
  product/ci/split_tests/utils/BUILD.bazel
  product/ci/split_tests/utils/consts.go
  product/ci/split_tests/utils/filetime.go
  product/ci/split_tests/utils/utils.go
Labels: go

#37235 fix: [CI-4581]: Skip test selection and cg collection in case of manual run
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
Labels: go

#37298 fix: [CI-5480]: go-scm lib bump
  WORKSPACE
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: go

#37373 fix: [CI-4581]: Fix SelectTests API response
  product/ci/addon/tasks/runtests.go
Labels: go

#37563 fix: [CI-4292]: SCM changes for bitbucket merge pr
  WORKSPACE
  product/ci/scm/converter/pr.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/proto/scm.proto
Labels: go

#37092 feat: [CI-5185]: RunTests with Parallelism
  product/ci/addon/tasks/BUILD.bazel
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/csharp/nunit_console.go
  product/ci/addon/testintelligence/java/BUILD.bazel
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/helper.go
  product/ci/addon/testintelligence/java/maven.go
  product/ci/addon/testintelligence/mocks/runner_mock.go
  product/ci/addon/testintelligence/runner.go
  product/ci/common/external/util.go
  product/ci/engine/proto/execution.proto
  product/ci/split_tests/utils/consts.go
  product/ci/ti-service/types/types.go
Labels: go

#37787 feat: [CI-3333]: Scala/Kotlin yaml change
  325-sto-beans/src/test/resources/schema/SecurityStage/all.json
  332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/TIBuildTool.java
  332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/TILanguage.java
  332-ci-manager/service/src/test/resources/schema/IntegrationStage/all.json
  332-ci-manager/service/src/test/resources/schema/IntegrationSteps/all.json
  commons/go/lib/utils/utils.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/testintelligence/java/BUILD.bazel
  product/ci/addon/testintelligence/java/sbt.go
Labels: go

#37834 feat: [CI-5425]: Add test autodetect support for Bazel
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/bazel_test.go
Labels: go

#38154 fix: [CI-3333]: SBT support - Missed file in previous commit
  product/ci/addon/tasks/runtests.go
  product/ci/addon/testintelligence/java/sbt.go
  product/ci/addon/testintelligence/java/sbt_test.go
Labels: go

#37896 fix: [SRM-12138] added to authorList and introduced RiskCategory entity and resource.
  300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskCategory.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskProfile.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/RiskCategoryDTO.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/RiskCategoryResource.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/RiskCategoryService.java
  300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/RiskCategoryServiceImpl.java
  300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java
  300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/RiskCategoryResourceTest.java
  300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/RiskCategoryServiceImplTest.java
  948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java
  990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
  scripts/jenkins/authorsList.txt
Labels: cv

#37915 feat: [CI-5557]: Added run command log in CI
  product/ci/addon/tasks/run.go
Labels: go
