Repository harness/harness-core, pull requests merged in 2022-04, with the labels that each got.

#31932 feat: [PL-23377]: SCM, Adding Azure findcommit
  product/ci/scm/git/azure_test.go
Labels: go

#32017 feat: [CDS-7771]: Updates `jsch` artifact for implementing `rsa-sha2-256` and `rsa-sha2-512`
  260-delegate/src/test/resources/dependenciesInRestCapsule.txt
  WORKSPACE
  project/main_maven_install.json
Labels: bug, enhancement, bazel, dependencies

#31990 feat: [PL-24335]: Add find repo support in scm
  120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateGroupTagsResource.java
  260-delegate/module-dependency.hash
  270-delegate-service-app/module-dependency.hash
  400-rest/src/main/java/io/harness/delegate/resources/DelegateTagsResource.java
  420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateDTO.java
  420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroupDTO.java
  420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTags.java
  420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateGroupTagsInternalResource.java
  860-orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/ResourceRestraintOrchestrationEndObserver.java
  860-orchestration-steps/src/test/java/io/harness/steps/resourcerestraint/ResourceRestraintOrchestrationEndObserverTest.java
  WORKSPACE
  product/ci/scm/git/BUILD.bazel
  product/ci/scm/git/git.go
  product/ci/scm/git/git_test.go
  product/ci/scm/git/testdata/repo.json
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/grpc/handler.go
  product/ci/scm/proto/scm.proto
Labels: gojava

#32188 [fix]: [CI-4057]: Handle the case where additional certs path is empty
  product/ci/scm/gitclient/gitclient.go
Labels: go

#32187 [fix]: [CI-2687]: Add nudge for bucket not existing
  product/ci/common/external/util.go
Labels: go

#32287 feat: [PL-24264]: Fetch commit id for file operations in azure
  product/ci/scm/file/file.go
  product/ci/scm/file/file_test.go
Labels: gojava
