Repository harness/harness-core, pull requests merged in 2022-06, with the labels that each got.

#33769 [Fix]: [CDS-38367]: Alters Junit to add logging checks
  125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java
Labels: enhancement

#34192 [Feat]: [CDS-38475]: Improves error handling for extracting text variables
  400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java
  400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java
  400-rest/src/test/java/software/wings/sm/states/provision/CloudFormationCreateStackStateTest.java
Labels: enhancement

#33741 feat: [CI-4372]: add dotnet support
  .github/workflows/go_build.yaml
  product/ci/addon/go.mod
  product/ci/addon/go.sum
  product/ci/addon/tasks/BUILD.bazel
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/addon/testintelligence/csharp/BUILD.bazel
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/csharp/dotnet_test.go
  product/ci/addon/testintelligence/csharp/nunit_console.go
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/engine/proto/tiproxy.proto
  product/ci/ti-service/client/client.go
  product/ci/ti-service/client/http.go
Labels: go

#34158 [Feat]: [CDS-2978]: Adds check to ignore CP Delegate Selector for Shell Script Step
  400-rest/src/main/java/software/wings/sm/states/ShellScriptState.java
  400-rest/src/test/java/software/wings/sm/states/ShellScriptStateTest.java
Labels: enhancement

#34445 feat: [CI-4781]: Include FileName from test XML reports
  product/ci/addon/gojunit/ingest.go
  product/ci/addon/gojunit/ingest_test.go
  product/ci/addon/gojunit/types.go
  product/ci/addon/testreports/junit/junit.go
  product/ci/addon/testreports/junit/junit_test.go
  product/ci/ti-service/types/types.go
Labels: go

#34690 techdebt: [SPG-122]: upgrade logback, [SPG-124]: upgrade google oauth client
  WORKSPACE
  project/main_maven_install.json
Labels: java

#34547 fix: [CI-3708]: Minor dotnet change fix
  product/ci/addon/tasks/runtests.go
Labels: gojava
