Repository harness/harness-core, pull requests merged in 2022-12, with the labels that each got.

#40804 feat: [PIE-6642]: add logic to work with gitClient for SSH type git connector
  136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java
  product/ci/scm/file/file.go
  product/ci/scm/proto/scm.proto
Labels: gojava

#40896 feat: [CI-6122]: Custom glob support for tests (K8s)
  commons/go/lib/utils/BUILD.bazel
  commons/go/lib/utils/utils.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/testintelligence/csharp/BUILD.bazel
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/csharp/helper.go
  product/ci/addon/testintelligence/csharp/helper_test.go
  product/ci/addon/testintelligence/csharp/nunit_console.go
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/bazel_test.go
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/helper.go
  product/ci/addon/testintelligence/java/maven.go
  product/ci/addon/testintelligence/java/sbt.go
  product/ci/addon/testintelligence/mocks/runner_mock.go
  product/ci/addon/testintelligence/runner.go
  product/ci/engine/proto/execution.proto
Labels: go

#40972 fix: [CI-5843]: Ignore instrumentation optimizations
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/csharp/dotnet_test.go
  product/ci/addon/testintelligence/csharp/nunit_console.go
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/gradle.go
  product/ci/addon/testintelligence/java/gradle_test.go
  product/ci/addon/testintelligence/java/maven.go
  product/ci/addon/testintelligence/java/maven_test.go
  product/ci/addon/testintelligence/java/sbt.go
  product/ci/addon/testintelligence/java/sbt_test.go
Labels: go

#41469 [feat]: [PIE-6124]: Adding custom metrics, Idle Timeout For Pending Stages
  queue-service/hsqs/README.md
  queue-service/hsqs/cmd/BUILD.bazel
  queue-service/hsqs/cmd/server.go
  queue-service/hsqs/handler/BUILD.bazel
  queue-service/hsqs/handler/handler.go
  queue-service/hsqs/handler/handler_test.go
  queue-service/hsqs/instrumentation/BUILD.bazel
  queue-service/hsqs/instrumentation/instrumentation.go
  queue-service/hsqs/instrumentation/metrics/BUILD.bazel
  queue-service/hsqs/instrumentation/metrics/metrics.go
  queue-service/hsqs/router/router.go
  queue-service/hsqs/store/redis/redis_store.go
Labels: go

#41310 feat: [CI-6259]: RunTests step log parity
  product/ci/addon/tasks/common.go
  product/ci/addon/tasks/plugin.go
  product/ci/addon/tasks/run.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/engine/proto/tiproxy.proto
Labels: gojava

#41564 [feat]: [PIE-7071]: Updating consumer key for ack operation
  260-delegate/src/test/java/software/wings/delegatetasks/k8s/MockFileSystem.java
  260-delegate/src/test/java/software/wings/delegatetasks/k8s/MockPath.java
  332-ci-manager/service/src/main/java/io/harness/ci/beans/execution/CIExecutionArgs.java
  332-ci-manager/service/src/main/java/io/harness/ci/beans/execution/QueueServiceClient.java
  queue-service/hsqs/store/redis/redis_store.go
Labels: go, gojava

#41555 [feat]: [CCM-9474]: Currency Preferences Data Pipeline
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/GcpSyncTasklet.java
  scripts/terraform/cloudfunctions/ce/ce-cf-resources.tf
  scripts/terraform/cloudfunctions/ce/src/python/aws_billing_bq_main.py
  scripts/terraform/cloudfunctions/ce/src/python/aws_billing_gcs_main.py
  scripts/terraform/cloudfunctions/ce/src/python/aws_currency_preference_historical_update.py
  scripts/terraform/cloudfunctions/ce/src/python/azure_billing_bq_main.py
  scripts/terraform/cloudfunctions/ce/src/python/azure_billing_cost_bq_main.py
  scripts/terraform/cloudfunctions/ce/src/python/azure_billing_gcs_main.py
  scripts/terraform/cloudfunctions/ce/src/python/azure_currency_preference_historical_update.py
  scripts/terraform/cloudfunctions/ce/src/python/bq_schema.py
  scripts/terraform/cloudfunctions/ce/src/python/gcp_billing_bq_main.py
  scripts/terraform/cloudfunctions/ce/src/python/gcp_currency_preference_historical_update.py
  scripts/terraform/cloudfunctions/ce/src/python/requirements.txt
  scripts/terraform/cloudfunctions/ce/src/python/util.py
Labels: do-not-merge

#41102 feat: [CDS-46920]: support linking of org/account level service/env
  120-ng-manager/src/main/java/io/harness/ng/core/EnvironmentValidationHelper.java
  120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java
  120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/ServiceEntityValidationHelper.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
  120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java
  125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupService.java
  125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java
  125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
  125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java
  125-cd-nextgen/src/test/java/io/harness/cdng/envGroup/mappers/services/EnvironmentGroupServiceImplTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResourceTest.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/mappers/InfrastructureFilterHelper.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImplTest.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImplTest.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntitySetupUsageHelperTest.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImplTest.java
  127-cd-nextgen-entities/src/test/resources/infrastructure-at-account-level.yaml
  127-cd-nextgen-entities/src/test/resources/infrastructure-at-org-level.yaml
  970-ng-commons/src/main/java/io/harness/NGResourceFilterConstants.java
  970-ng-commons/src/main/java/io/harness/beans/InfraDefReference.java
  970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java
  970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java
Labels: CDNG

#41631 feat: [cds-41332]: Added Service schema validation for new service env redesign
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/OrgServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceEntityYamlSchemaHelper.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
  120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ProjectServicesApiImplTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceEntityYamlSchemaHelperTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceV2Test.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: CDNG

#41603 feat: [cds-48173]: moving rbac check from service step to individual steps
  125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
  125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/artifact/steps/ArtifactsStepV2Test.java
  125-cd-nextgen/src/test/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2Test.java
  125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/steps/ManifestsStepV2Test.java
  125-cd-nextgen/src/test/java/io/harness/cdng/service/steps/ServiceStepV3Test.java
Labels: CDNG

#41680 feat: [CDS-46287]: create provisioner plan node for gitops
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
Labels: CDNG

#41430 feat: [cds-48312]: Error handling for getTemplates with GitX fallback branch
  840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java
Labels: CDNG

#41650 feat: [CDS-46287]: configure rollback node for v2 env provisioning
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/rollback/RollbackPlanCreator.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreatorTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreatorTest.java
Labels: CDNG

#38550 [feat]: [cds-44553]: Iterator Freeze initial commit
  120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java
  120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java
  125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java
  125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java
  125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java
  125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java
  125-freeze/src/test/java/io/harness/freeze/helpers/FreezeTimeUtilsTest.java
  959-ng-persistence/src/main/java/io/harness/mongo/iterator/provider/SpringPersistenceProvider.java
  959-ng-persistence/src/main/java/io/harness/mongo/iterator/provider/SpringPersistenceRequiredProvider.java
Labels: CDNG
