Repository harness/harness-core, pull requests merged in 2022-05, with the labels that each got.

#32721 feat: [CI-3878]: add always run annotation
  product/ci/addon/parser/cg/callgraph.go
  product/ci/addon/parser/cg/callgraph_test.go
Labels: go

#32556 fix: [CI-4002]: Pass context to the APIs in the TI service HTTP Client
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/engine/main.go
  product/ci/ti-service/client/client.go
  product/ci/ti-service/client/http.go
Labels: go

#32910 [feat]: [CI-4385]: fix UTs
  product/ci/addon/services/service_test.go
  product/ci/addon/tasks/plugin_test.go
  product/ci/addon/tasks/run_test.go
Labels: go

#33032 [feat]: [PL-24910]: Upgrading go-scm library in scm service
  WORKSPACE
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: go

#33324 fix: [CI-4502]: Fix typo when Run step is canceled due to signal
  product/ci/engine/new/executor/step_executor.go
Labels: go

#33354 Fix: [CDS-37670]: Adds logic to include logs for git 'template file' fetch
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationDeleteStackState.java
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationRollbackStackState.java
  400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java
  400-rest/src/test/java/software/wings/sm/states/provision/CloudFormationCreateStackStateTest.java
Labels: bug

#33374 [feat]: [CI-4445]: Fix manifest for windows build
  product/ci/addon/docker/manifest.tmpl
  product/ci/engine/docker/manifest.tmpl
Labels: go

#33377 [fix]: [PL-25184]: Fix the failing unit tests in go scm
  product/ci/scm/file/BUILD.bazel
  product/ci/scm/file/file.go
  product/ci/scm/file/file_test.go
  product/ci/scm/file/testdata/CommitsOfFile.json
  product/ci/scm/grpc/handler_test.go
  product/ci/scm/grpc/testdata/CommitsOfFile.json
Labels: go

#33394 [fix]: [PL-25293]: Add support for commitID in bitbucket server
  952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java
  product/ci/scm/file/file.go
  product/ci/scm/git/git.go
Labels: go, gojava

#33528 [feat]: [PL-25413]: Add the support for returning commitId while creating file
  product/ci/scm/file/file.go
  product/ci/scm/git/git.go
Labels: go

#33370 feat: [CI-4372]: add dotnet extra fields support
  260-delegate/module-dependency.hash
  270-delegate-service-app/module-dependency.hash
  320-ci-execution/src/main/java/io/harness/ci/serializer/RunTestsStepProtobufSerializer.java
  320-ci-execution/src/main/java/io/harness/ci/serializer/vm/VmRunTestStepSerializer.java
  320-ci-execution/src/test/java/io/harness/ci/creator/variables/RunTestStepVariableCreatorTest.java
  325-sto-beans/src/test/resources/schema/SecurityStage/all.json
  330-ci-beans/src/main/java/io/harness/beans/serializer/RunTimeInputHandler.java
  330-ci-beans/src/main/java/io/harness/beans/steps/stepinfo/RunTestsStepInfo.java
  330-ci-beans/src/main/java/io/harness/beans/yaml/extended/TIDotNetBuildEnvName.java
  330-ci-beans/src/main/java/io/harness/beans/yaml/extended/TIDotNetVersion.java
  330-ci-beans/src/test/resources/schema/IntegrationStage/all.json
  330-ci-beans/src/test/resources/schema/IntegrationSteps/all.json
  930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVMExecuteStepTaskHandler.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/runner/ExecuteStepRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/steps/VmRunTestStep.java
  product/ci/engine/proto/execution.proto
Labels: gojava

#33579 [feat]: [PL-25416]: Git to Harness fix: Fix the issue where we are not able t…
  product/ci/scm/file/file.go
Labels: go

#33510 [Feat]: [CDS-35675] Adds logs to Infrastructure Step on NG
  125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceSpecStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java
Labels: enhancement
