Repository harness/harness-core, pull requests merged in 2023-10, with the labels that each got.

#52675 techdebt: [CDS-75403]: Ignore flaky unit test
  400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceRollbackTest.java
Labels: java

#53519 fix: [PL-40351]: Added Description in API Docs and set the default values internally
  400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
  400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java
  920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSetupDetails.java
Labels: pl

#52844 feat: [PL-41114]: removing pending invites for a user being invited via scim
  120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java
  400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/main/java/software/wings/service/intfc/UserService.java
  400-rest/src/test/java/software/wings/scim/ScimUserServiceTest.java
Labels: pl

#53278 [feat]: [PL-41291]: add uniqueId for project and org entity during creation, updation
  120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java
  959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java
  959-ng-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java
  960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java
  960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAware.java
  960-persistence/src/main/java/io/harness/serializer/morphia/PersistenceMorphiaRegistrar.java
Labels: pl

#52635 feat: [PL-39453]: Upon deletion of secret from Harness, purge them from azure key vault
  120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
  400-rest/src/main/java/software/wings/service/impl/security/NGSecretManagerServiceImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/AzureKeyVaultDTOToEntity.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/AzureKeyVaultEntityToDTO.java
  440-connector-nextgen/src/test/resources/schema/Connectors/all.json
  890-sm-delegate/src/main/java/io/harness/ng/AzureKeyVaultConfigDTOMapper.java
  931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
  931-encryption-service/src/test/io/harness/encryptors/clients/AzureVaultEncryptorTest.java
  931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java
  931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java
  940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultConfigDTO.java
  940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultMetadataRequestSpecDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/AzureKeyVaultConnectorDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/outcome/AzureKeyVaultConnectorOutcomeDTO.java
Labels: pl

#53250 feat: [PL-40108]: add oauthEnabled to AuthenticationSettings
  122-ng-authentication-settings/BUILD.bazel
  122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/dtos/AuthenticationSettingsResponse.java
  122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java
  122-ng-authentication-settings/src/test/java/io/harness/ng/authenticationsettings/AuthenticationSettingServiceImplTest.java
  123-ng-core-user/src/main/java/io/harness/ng/authenticationsettings/remote/AuthSettingsManagerClient.java
  400-rest/src/main/java/software/wings/resources/AccountResourceNG.java
  970-ng-commons/src/main/java/io/harness/common/AccountAuthenticationSettings.java
Labels: pl

#53726 feat: [CI-9643]: make rspec helper change automatically
  product/ci/addon/testintelligence/ruby/helper.go
  product/ci/addon/testintelligence/ruby/rspec.go
Labels: go

#53289 feat: [CHAOS-715]: Deletion of Environment should not be allowed if any chaos infrastructure is associated with the same.
  120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosInfrastructureRequest.java
  120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosResource.java
  120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosService.java
  120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/event/SetupUsageChangeEventMessageListener.java
  970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java
  970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java
  970-ng-commons/src/main/java/io/harness/entities/EntityType.java
  970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto
  970-ng-commons/src/test/java/io/harness/EntityTypeTest.java
Labels: enhancement

#53769 [fix]: [CI-8871]: scm, warn on FindFile miss
  product/ci/scm/file/file.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: go

#53635 [feat]: [CDS-80682]: Update and Get Flow for GitX-ENV
  120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java
  120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2Test.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustom.java
  127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/spring/EnvironmentRepository.java
Labels: do-not-merge

#53729 [feat]: [PL-41293]: add parentId for Org and Project create/update flow
  120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/remote/ProjectResourceTest.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/OrganizationBackgroundMigrationDetails.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/parentid/AddParentIdToOrganizationMigration.java
Labels: pl

#53981 [feat]: [PL-41293]: add parentId migration for existing Project entities
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/ProjectBackgroundMigrationDetails.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/parentid/AddParentIdToProjectMigration.java
Labels: pl

#54047 [feat]: [PL-41293]: move uniqueId, parentId migration for org, project under common provider
  120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/ProjectBackgroundMigrationDetails.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/ProjectMigrationProvider.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/UniqueIdParentIdBackgroundMigrationDetails.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/UniqueIdParentIdMigrationProvider.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/schema/UniqueIdParentIdSchema.java
Labels: pl

#53582 feat: [CI-9328]: scm service get latest commit should use list commits
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
  310-iacm-manager/config/iacm-manager-config.yml
  332-ci-manager/app/src/main/java/io/harness/ci/CIManagerConfiguration.java
  332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java
  332-ci-manager/app/src/test/java/io/harness/app/impl/CIManagerRule.java
  332-ci-manager/build.properties
  332-ci-manager/chart/templates/config.yaml
  332-ci-manager/config/ci-manager-config.yml
  332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/ConnectorUtils.java
  332-ci-manager/service/src/test/java/io/harness/ci/executionplan/rule/CIExecutionRule.java
  332-ci-manager/service/src/test/java/io/harness/ci/states/codebase/CodeBaseStepTest.java
  879-pipeline-ci-commons/src/main/java/io/harness/ci/utils/BaseConnectorUtils.java
  933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
  933-ci-commons/src/test/java/io/harness/ci/git/checks/GitStatusCheckHelperTest.java
  952-scm-java-client/src/test/java/io/harness/impl/scm/ScmServiceClientImplTest.java
  960-api-services/src/main/java/io/harness/git/GitClientHelper.java
  960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java
  WORKSPACE
  product/ci/scm/docker/Dockerfile
  product/ci/scm/git/BUILD.bazel
  product/ci/scm/git/git.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/parser/testdata/harness_pr.json.golden
Labels: gojava

#54092 fix: [PL-41502]: Create and Modify Indexes in order to support better querying over audit events collection
  platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java
Labels: pl

#54235 fix: [CI-9773]: Ignore test report upload failure for Run/RunTests step
  WORKSPACE
  product/ci/addon/tasks/run.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/engine/proto/ti_service_proxy.proto
Labels: go

#54305 fix: [CI-9933]: Improve logging for scanner token too long errors
  product/ci/addon/tasks/BUILD.bazel
  product/ci/addon/tasks/common.go
  product/ci/addon/tasks/common_test.go
  product/ci/addon/tasks/testdata/long_output.txt
  product/ci/addon/tasks/testdata/short_output.txt
Labels: go

#54310 fix:[PL-42015]: When listing role fixed its referenced by count for each principal type.
  access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java
  access-control/libs/core/src/test/java/io/harness/accesscontrol/roles/RoleServiceImplTest.java
Labels: pl

#54342 feat:[PL-41230]: On recording Role audits, adding details of role change.
  access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleRequest.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java
  access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java
Labels: pl

#54349 [fix]: [CDS-82089]: Set the stage/step name from originalNodeExecution instead of identityNode in rety-failed-pipeline with matrix
  pipeline-service/modules/orchestration-steps/src/test/java/io/harness/engine/pms/execution/strategy/IdentityStrategyInternalStepTest.java
  pipeline-service/modules/orchestration-steps/src/test/java/io/harness/engine/pms/execution/strategy/IdentityStrategyStepTest.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelper.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyStep.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyTest.java
Labels: do-not-merge

#54374 fix: [PL-42050]: Fix for custom sm exception - RunTime Inputs are not provided
  120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
Labels: pl

#54373 [fix]: [CDS-81724]: secret resolution for custom artifact input variables
  120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
  120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtilsTest.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/custom/CustomResourceServiceImpl.java
  125-cd-nextgen/src/test/java/io/harness/cdng/artifact/resources/custom/CustomResourceServiceImplTest.java
Labels: do-not-merge

#54438 [fix]: [PL-42074]: user emails provided in update user group v2 API require user to be converted to lowercase
  123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java
Labels: pl

#54221 [feat]: [PL-42024]: add background migration job for unique, parentId in Projects and Organizations
  120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java
  120-ng-manager/src/main/java/io/harness/ng/core/entities/migration/NGManagerUniqueIdParentIdMigrationStatus.java
  120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesJob.java
  120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java
  120-ng-manager/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrars.java
Labels: pl

#54478 [feat]: [CI-9958]: Modify command to get changed files for push trigger
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/common/external/util.go
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/engine/legacy/steps/runtests.go
  product/ci/engine/new/executor/runtests/runtests.go
  product/ci/engine/proto/ti_service_proxy.proto
Labels: go

#54552 fix: [CDS-82380]: additional empty checks for release metadata fields
  960-api-services/src/main/java/io/harness/k8s/K8sReleaseDiffCalculator.java
  960-api-services/src/test/java/io/harness/k8s/K8sReleaseDiffCalculatorTest.java
Labels: do-not-merge

#54594 [feat]: [PL-42024]: use TypeAlias name if present for entityClassName
  120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java
  build.properties
Labels: pl

#54098 [feat]: [PL-41294]: ng api to return Scope details from scope identifiers
  120-ng-manager/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java
  120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/remote/ScopeInfoResource.java
  120-ng-manager/src/main/java/io/harness/ng/serializer/kryo/NGCacheDataKryoRegistrar.java
  120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java
  400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/ScopeInfoModule.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ScopeInfoService.java
  clients/scope/BUILD.bazel
  clients/scope/src/main/java/io/harness/scopeinfoclient/ScopeInfoClientModule.java
  clients/scope/src/main/java/io/harness/scopeinfoclient/remote/ScopeInfoClient.java
  clients/scope/src/main/java/io/harness/scopeinfoclient/remote/ScopeInfoClientHttpFactory.java
Labels: pl
