Repository harness/harness-core, pull requests merged in 2023-02, with the labels that each got.

#43097 [feat]: [CI-6692]: Support for Shell Python in Run steps
  315-sto-manager/app/src/test/resources/schema/SecurityStage/all.json
  332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/beans/Shell.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/BackgroundStepProtobufSerializer.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/RunStepProtobufSerializer.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
  332-ci-manager/service/src/test/resources/schema/IntegrationStage/all.json
  332-ci-manager/service/src/test/resources/schema/IntegrationSteps/all.json
  835-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/CIShellType.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerRunStepHelper.java
  pipeline-service/modules/orchestration-steps/src/test/resources/schema/ApprovalStage/all.json
  pipeline-service/modules/orchestration-steps/src/test/resources/schema/PipelineSteps/all.json
  pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json
  product/ci/addon/tasks/run.go
  product/ci/engine/proto/execution.proto
Labels: gojava

#43333 [feat]: [CI-6692]: Support for Shell Python in Run steps
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
  product/ci/addon/tasks/run.go
Labels: gojava

#42370 [feat]: [CI-5875]: Upgrade and Test GO to 1.19.4
  .bazelversion
  WORKSPACE
Labels: gojava

#43409 feat: [CDS-52632]: K8s declarative rollback opt-in configuration
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeMapper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDeleteStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sRollingRollbackStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java
  125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/K8sManifestOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/KustomizeManifestOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OpenshiftManifestOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/K8sManifest.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifest.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/OpenshiftManifest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sTestHelper.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: CDNG

#43639 [fix]: [CI-6954]: error running update-repos
  WORKSPACE
Labels: gojava

#43634 feat: [CI-6807]: add harness code to scm service
  WORKSPACE
  product/ci/scm/.gitignore
  product/ci/scm/file/file.go
  product/ci/scm/file/harness_test.go
  product/ci/scm/git/harness_test.go
  product/ci/scm/gitclient/BUILD.bazel
  product/ci/scm/gitclient/gitclient.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/proto/scm.proto
Labels: go

#43808 [feat]: [CI-6807]: scm, adding further harness code functionality
  WORKSPACE
  product/ci/scm/git/git.go
  product/ci/scm/git/harness_test.go
  product/ci/scm/go.mod
  product/ci/scm/go.sum
  product/ci/scm/parser/BUILD.bazel
  product/ci/scm/parser/parser.go
  product/ci/scm/parser/parser_test.go
  product/ci/scm/parser/testdata/harness_pr.json
  product/ci/scm/parser/testdata/harness_pr.json.golden
  product/ci/scm/proto/scm.proto
  product/ci/scm/repo/harness_test.go
  product/ci/scm/repo/repo.go
Labels: go

#43954 [feat]: [CI-6692]: Change entrypoint for py in windows K8
  product/ci/addon/tasks/run.go
Labels: gojava

#43945 [fix]: [CDS-53078]: allow empty string as input for an an object runtime field
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceYamlV2.java
  125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java
  960-yaml-sdk/src/main/java/io/harness/yaml/schema/YamlSchemaGenerator.java
  960-yaml-sdk/src/main/java/io/harness/yaml/schema/beans/SchemaConstants.java
  960-yaml-sdk/src/main/java/io/harness/yaml/schema/beans/SupportedPossibleFieldTypes.java
  960-yaml-sdk/src/test/java/io/harness/yaml/schema/beans/YamlSchemaConstantsTest.java
Labels: draft

#44112 fix: [CI-7096]: Refactor TI client
  product/ci/common/external/util.go
  product/ci/engine/grpc/BUILD.bazel
  product/ci/engine/grpc/tiproxy_handler.go
  product/ci/split_tests/ti/ti_helper.go
  product/ci/ti-service/client/client.go
  product/ci/ti-service/client/http.go
Labels: go

#44109 fix: [CCM-11244]: Update cache key for GCP Sync to include tableId
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/GcpSyncTasklet.java
Labels: do-not-merge

#44174 techdebt: [CDS-53907]: disable unwanted long running CG unit tests
  260-delegate/src/test/java/software/wings/delegatetasks/aws/ecs/ecstaskhandler/EcsServiceDeployCommandHandlerTest.java
  400-rest/src/test/java/software/wings/scheduler/artifact/ArtifactCleanupHandlerTest.java
  400-rest/src/test/java/software/wings/service/WorkflowExecutionServiceDBTest.java
Labels: java

#44014 [fix]: [CI-3710]: Proto files have conflicting names with case
  953-events-api/src/main/proto/io/harness/eventsframework/schemas/webhookpayloads/webhookdata.proto
  pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/triggers/trigger_payload.proto
  product/ci/engine/proto/BUILD.bazel
  product/ci/engine/proto/log_service_proxy.proto
  product/ci/engine/proto/ti_service_proxy.proto
  product/ci/scm/proto/BUILD.bazel
  product/ci/scm/proto/scm_service.proto
Labels: gojava

#44381 [fix]: [PIE-8477]: Making http logs configurable for queue Service
  queue-service/hsqs/config/config.go
  queue-service/hsqs/router/router.go
Labels: go

#44418 [feat]: [PIE-7702]: Adding version API's for Queue Service
  332-ci-manager/config/ci-manager-config.yml
  970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java
  pipeline-service/config/config.yml
  queue-service/hsqs/build.properties
  queue-service/hsqs/build/build_jar.sh
  queue-service/hsqs/build/container/Dockerfile-ubi
  queue-service/hsqs/cmd/server.go
  queue-service/hsqs/config/config.go
  queue-service/hsqs/router/router.go
Labels: go
