Repository harness/harness-core, pull requests merged in 2023-12, with the labels that each got.

#56145 techdebt: [CDS-84452]: cleanup code for FF GITOPS_UPDATE_APP_STEP
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: java

#56170 feat: [CDS-85650]: Implement and test CRUD operations for webhook triggers v1
  pipeline-service/contracts/openapi/v1/openapi.yaml
  pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java
  pipeline-service/service/src/main/java/io/harness/pms/triggers/v1/NGTriggerApiUtils.java
  pipeline-service/service/src/main/java/io/harness/pms/triggers/v1/NGWebhookTriggerApiUtils.java
Labels: yaml-simpl

#56104 feat:[CDS-84540]: Adding support for Aws S3 Store Download For Serverless Manifest and Values Manifest in Serverless V2 Swimlane
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestsStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessDownloadManifestV2StepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestStepHelperTest.java
Labels: cd-deployments, cd-serverlessV2

#56053 feat: [CDS-83806]: Service name for account/org level service is coming as 'Deleted' on subscriptions page.
  110-change-data-capture/src/main/java/io/harness/changehandlers/ServicesChangeDataHandler.java
  120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/AddFullyQualifiedIdentifierColumnToServices.java
  120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreTimeScaleMigrationDetails.java
  120-ng-manager/src/main/resources/timescale/add_fully_qualified_identifier_column_to_services.sql
  125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java
  125-cd-nextgen/src/test/java/io/harness/cdng/usage/CDLicenseUsageDALTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java
  959-psql-database-models/src/generated/java/io/harness/timescaledb/tables/Services.java
  959-psql-database-models/src/generated/java/io/harness/timescaledb/tables/pojos/Services.java
  959-psql-database-models/src/generated/java/io/harness/timescaledb/tables/records/ServicesRecord.java
Labels: cds-licensing

#56221 [feat]: [CCM-15278]: Added HMAC access key and secret key in helm charts
  batch-processing/chart/Chart.lock
  batch-processing/chart/Chart.yaml
  batch-processing/chart/README.md
  batch-processing/chart/charts/harness-common-1.2.1.tgz
  batch-processing/chart/charts/harness-common-1.3.0.tgz
  batch-processing/chart/templates/_helpers.tpl
  batch-processing/chart/templates/statefulset.yaml
  batch-processing/chart/values.yaml
Labels: do-not-merge

#55778 techdebt: [CDS-84693]: Remove cds asg v2 FF
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge

#56190 fix: [CDS-84962]: Fixed missing logs from Cloudformation delete stack…
  125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java
  878-ng-common-utilities/src/main/java/io/harness/logstreaming/ILogStreamingStepClient.java
  878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java
Labels: cd-deployments

#56272 feat:[CDS-84541]: Adding support for Aws S3 Store Download For SAM Manifest and Values Manifest in SAM Swimlane
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/AwsSamStepHelperTest.java
Labels: cd-deployments, cd-sam

#56279 feat: [CDS-85719]: NG manager and delegate side changes for token bas…
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/tasconnector/TasManualCredential.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/tasmapper/TasDTOToEntity.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/tasmapper/TasEntityToDTO.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfDataFetchCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfDeployCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfRollbackCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfRollingDeployCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfRollingRollbackCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfRouteMappingCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfSwapRollbackCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfSwapRouteCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/TasBasicSetupTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/TasBlueGreenSetupTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/TasRunPluginCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/pcf/TasTaskHelperBase.java
  932-connector-task/src/main/java/io/harness/connector/task/tas/TasNgConfigMapper.java
  932-connector-task/src/main/java/io/harness/connector/task/tas/TasValidationHandler.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/tasconnector/TasManualDetailsDTO.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
  960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryClientProvider.java
  970-api-services-beans/src/main/java/io/harness/pcf/model/CfRenameRequest.java
  970-api-services-beans/src/main/java/io/harness/pcf/model/CfRequestConfig.java
  970-api-services-beans/src/main/java/io/harness/pcf/model/CloudFoundryConfig.java
Labels: cd-deployments, cd-pcf

#56172 [feat]: [CDS-81942]: adding Deployment Stage Filter Json Creator
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreatorTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStagePlanCreatorTest.java
  125-cd-nextgen/src/test/resources/v1/cdng/creator/servicePlanCreator/pipeline.yaml
  125-cd-nextgen/src/test/resources/v1/deployStageWithEnvironmentAndProvisioner.yaml
  125-cd-nextgen/src/test/resources/v1/deployStageWithEnvironmentAndProvisionerDuplicateIdentifiers.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/deployStageWithEnvironmentGroupAndFilters.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/deployStageWithEnvironmentGroupAndFiltersRuntime.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/deployStageWithMultiEnvironments.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/deployStageWithMultiEnvironmentsAndFilterAsRuntime.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/deployStageWithMultiEnvironmentsAndFilters.yaml
  125-cd-nextgen/src/test/resources/v1/multisvcinfra/gitops/deployStageWithEnvironmentAndFilter.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithParallelStagesAndUseFromStageReferredStageExists.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithParallelStagesAndUseFromStageReferredStageExists2.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithParallelStagesAndUseFromStageReferredStageExists3.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithParallelStagesAndUseFromStageReferredStageNotExists.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithParallelStagesAndUseFromStageReferredStageNotExists2.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithUseFromStageReferredStageNotExists.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithUseFromStageReferredStageNotExistsForEnvironment.yaml
  125-cd-nextgen/src/test/resources/v1/pipelineWithUseFromStageReferredStageNotExistsForMultiServices.yaml
  125-cd-nextgen/src/test/resources/v1/stageTemplateSpecWithUsageFromStageFromEnvironment.yaml
  125-cd-nextgen/src/test/resources/v1/stageTemplateSpecWithUseFromStage.yaml
  125-cd-nextgen/src/test/resources/v1/stageTemplateSpecWithUseFromStageForServices.yaml
  125-cd-nextgen/src/test/resources/v1/validateMultiServices.yaml
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
Labels: cd-deployments

#56240 techdebt: [CDS-71861]: Clean up CDS_K8S_SERVICE_HOOKS_NG FF
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/helm/NativeHelmStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-kubernetes, cd-deployments

#56379 fix: [CDS-86215]: fix NPE during Git fetch task exception handling
  400-rest/src/test/java/software/wings/service/impl/yaml/GitClientHelperTest.java
  960-api-services/src/main/java/io/harness/git/ExceptionSanitizer.java
  960-api-services/src/test/java/io/harness/git/ExceptionSanitizerTest.java
Labels: cd-deployments, cd-pcf

#56184 fix: [CDS-85576]: rezolve expressions in pcf manifest
  400-rest/src/main/java/software/wings/sm/states/pcf/MapRouteState.java
  400-rest/src/main/java/software/wings/sm/states/pcf/PcfDeployState.java
  400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java
  400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java
  400-rest/src/main/java/software/wings/sm/states/pcf/PcfSwitchBlueGreenRoutes.java
  400-rest/src/test/java/software/wings/sm/states/pcf/PcfSetupStateTest.java
  400-rest/src/test/java/software/wings/sm/states/pcf/PcfStateHelperTest.java
  930-delegate-tasks/src/main/java/software/wings/helpers/ext/pcf/request/CfCommandSetupRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/PcfManifestsPackage.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/request/CfCommandDeployRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/request/CfCommandTaskParameters.java
Labels: cd-deployments, cd-pcf

#56316 techdebt: [CDS-74325]: Remove CDS_MULTI_SERVICE_PROPAGATION from code
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge

#56302 techdebt: [CDS-82368]: Clean up CDS_TERRAGRUNT_CLI_OPTIONS_NG FF
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStep.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge

#56433 fix: [CDS-86297]: tempRoute from BG App Setup should not be maped to Inactive app after Swap Rollback
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfSwapRollbackCommandTaskHandlerNG.java
  930-delegate-tasks/src/test/java/io/harness/delegate/pcf/CfSwapRollbackCommandTaskHandlerTest.java
Labels: cd-deployments, cd-pcf

#56402 feat: [CDS-80212]: Update get_active_services_by_date_function for La…
  120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreTimeScaleMigrationDetails.java
  120-ng-manager/src/main/resources/timescale/get_active_services_by_date_function_timescale.sql
Labels: cds-licensing

#56423 feat: [CDS-85996]: CG - Update License calculation for Lambda deploym…
  400-rest/src/main/java/io/harness/cdlicense/bean/CgCdLicenseUsageConstants.java
  400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java
Labels: cds-licensing

#56305 techdebt: [CDS-84682]: Remove CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG ff
  120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceEntityYamlSchemaHelperTest.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/steps/ManifestsStepV2Test.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityYamlSchemaHelper.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge, cd-kubernetes, cd-deployments

#56362 techdebt: [CDS-85874]: CDS-85876 Clean up trigger ff for trigger catalog
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge

#56553 feat: [CI-10532]: Proto changes for output variables in CI
  260-delegate/src/test/resources/kryo-registrations.txt
  400-rest/src/test/resources/manager-kryo-registrations.txt
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/stepstatus/StepOutputV2.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/stepstatus/StepStatus.java
  950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
  product/ci/addon/proto/addon.proto
  product/ci/engine/proto/execution.proto
Labels: go

#55319 fix: [CI-10258]: Add transport with certs for getting image entrypoint
  commons/go/lib/images/image.go
  commons/go/lib/images/image_test.go
  product/ci/common/external/util.go
  product/ci/engine/grpc/engine_handler.go
  product/ci/engine/grpc/engine_handler_test.go
Labels: go

#56028 feat:[CDS-75291]: Added kubernetes java client support for canary and traffic shift step CG
  260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java
  260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandlerTest.java
  400-rest/src/main/java/software/wings/sm/states/k8s/K8sCanaryDeploy.java
  400-rest/src/main/java/software/wings/sm/states/k8s/K8sTrafficSplitState.java
  400-rest/src/test/java/software/wings/sm/states/k8s/K8sCanaryDeployTest.java
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesResizeCommandUnit.java
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java
  930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
  930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sCanaryDeployTaskParameters.java
  930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sTrafficSplitTaskParameters.java
  960-api-services/src/main/java/io/harness/k8s/K8sApiVersion.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerService.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
  960-api-services/src/test/java/io/harness/k8s/KubernetesContainerServiceImplTest.java
Labels: cd-kubernetes, cd-deployments

#56249 feat:[CDS-85699]: removing fabric8 from kubernetes resize and kubernetes setup step
  400-rest/src/main/java/software/wings/utils/artifacts/DockerArtifactCommands.java
  400-rest/src/test/java/software/wings/beans/CommandUnitDescriptorTest.java
  400-rest/src/test/java/software/wings/beans/command/KubernetesResizeCommandUnitTest.java
  400-rest/src/test/java/software/wings/beans/command/KubernetesSetupCommandUnitTest.java
  400-rest/src/test/java/software/wings/helpers/ext/helm/HelmDeployServiceImplTest.java
  400-rest/src/test/java/software/wings/integration/KubernetesIntegrationTestBase.java
  400-rest/src/test/java/software/wings/integration/KubernetesYamlIntegrationTestBase.java
  400-rest/src/test/java/software/wings/service/ContainerServiceTest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/containerdeployment/ContainerDeploymentDelegateBaseHelper.java
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesResizeCommandUnit.java
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelperTest.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerService.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java
  960-api-services/src/test/java/io/harness/k8s/KubernetesContainerServiceImplTest.java
Labels: cd-kubernetes, cd-deployments

#56411 feat: [CDS-82481] Add traffic routing for K8s BG deployment step [Istio provider] - delegate
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStepParameters.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepParametersCommandUnitsTest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/K8sTrafficRoutingHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingCommon.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapperTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/K8sTrafficRoutingHelperTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingCommonTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/client/K8sApiClientTest.java
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService1.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService2.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService3.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService4.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService5.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceAuthorityRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceHeaderRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceMethodRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServicePortRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceSchemeRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceUriRule.yaml
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
  950-delegate-tasks-beans/src/test/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfigTest.java
  960-api-services/src/main/java/io/harness/k8s/K8sCommandUnitConstants.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/BUILD.bazel
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/HttpVirtualServiceSpec.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/Match.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/Metadata.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/TCPVirtualServiceSpec.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/TlsVirtualServiceSpec.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/VirtualServiceSpec.java
  970-api-services-beans/src/test/java/io/harness/k8s/model/istio/MatchTest.java
  970-api-services-beans/src/test/java/io/harness/k8s/model/istio/VirtualServiceTest.java
Labels: cd-kubernetes, cd-deployments

#56418 feat:[CDS-84539]: Generic Harness Store Download Step NG Manager Change
  120-ng-manager/config.yml
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java
  125-cd-nextgen/src/main/java/io/harness/cdng/NGModule.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/ContainerStepGroupHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepNode.java
  125-cd-nextgen/src/main/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepParameters.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/containerStepGroup/DownloadHarnessStoreStepPlanCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/containerStepGroup/DownloadHarnessStoreStepVariableCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java
  125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/CDStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadHarnessStorePluginInfoProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/containerStepGroup/DownloadHarnessStoreStepInfoVisitorHelper.java
  125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java
  125-cd-nextgen/src/test/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/containerStepGroup/DownloadHarnessStoreStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/DownloadHarnessStorePluginInfoProviderTest.java
  125-cd-nextgen/src/test/resources/recaster/alias/alias.txt
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java
  127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java
  127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java
  879-pipeline-ci-commons/src/main/java/io/harness/cdng/plugininfoproviders/PluginExecutionConfig.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
  970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java
  970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java
  970-ng-commons/src/main/java/io/harness/entities/EntityType.java
  970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto
  970-ng-commons/src/test/java/io/harness/EntityTypeTest.java
  pipeline-service/config/config.yml
Labels: cd-deployments, cd-containerStepGroup

#56630 [feat]: [CI-9899]: Parse filename in cypress juint xml
  product/ci/addon/gojunit/ingest.go
  product/ci/addon/gojunit/ingest_test.go
  product/ci/addon/gojunit/ingesters.go
  product/ci/addon/gojunit/testdata/cypress-custom.xml
  product/ci/addon/gojunit/testdata/cypress.xml
  product/ci/addon/tasks/plugin.go
  product/ci/addon/tasks/run.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/addon/testreports/junit/junit.go
  product/ci/addon/testreports/junit/junit_test.go
  product/ci/addon/testreports/reporter.go
Labels: go

#56635 techdebt: [CDS-86671]: Remove CDS_TF_TG_SKIP_ERROR_LOGS_COLORING from code
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStepV2.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStep.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-deployments, cd-infra-provisioners

#56602 [feat]: [CCM-15216]: Added bucket name prefix in configMap
  490-ce-commons/src/main/java/io/harness/ccm/clickHouse/ClickHouseConstants.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/beans/config/ClickHouseConfig.java
  batch-processing/build/container/scripts/replace_configs.sh
  batch-processing/chart/README.md
  batch-processing/chart/templates/config.yaml
  batch-processing/chart/templates/rolebinding.yaml
  batch-processing/chart/values.yaml
  batch-processing/service/batch-processing-config.yml
  batch-processing/service/src/main/java/io/harness/batch/processing/config/GcpSyncSmpConfig.java
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/GcpSyncTasklet.java
  ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java
Labels: do-not-merge

#56537 fix:[CDS-86418]: fixing NPE while reading decryptable entity types in for AWS connector.
  930-delegate-tasks/src/main/java/io/harness/delegate/task/config/ManifestDelegateConfigHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
Labels: pending-tests, cd-kubernetes, cd-deployments

#56623 fix: [CDS-86255]: Artifact Name should be shown instead of Artifact bundle name in Instance DashBoard
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBGAppSetupStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBasicAppSetupStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasCanaryAppSetupStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasRollingDeployStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/tas/TasRollingDeployStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/tas/TasStepHelperTest.java
  126-instance/src/main/java/io/harness/entities/ArtifactBundleInfo.java
  126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java
Labels: cd-deployments, cd-pcf

#56700 fix: [CI-8872]: fix logging
  product/ci/scm/file/file.go
  product/ci/scm/git/git.go
Labels: gojava

#56589 fix: [CDS-85942]: improving logs when manifest identifier is missing in service identifiers
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidatorTest.java
Labels: cd-kubernetes, cd-deployments

#56725 fix:[CDS-86839]: Removed Unsupported Exception thrown while instantiating the K8s setup and resize command unit
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesResizeCommandUnit.java
  930-delegate-tasks/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java
Labels: cd-kubernetes, cd-deployments, L1-Reviewed

#56733 fix: [CDS-77833]: provide empty file content when content is null
  877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java
  877-filestore/src/test/java/io/harness/filestore/service/FileStoreServiceImplTest.java
Labels: cd-deployments

#56220 fix: [CDS-84922]: k8s/helm delegate task interrupt improvements
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/rolling/K8sRollingBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sngtask/K8sTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java
  960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
  960-api-services/src/main/java/io/harness/retry/RetryHelper.java
  960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java
  970-api-services-beans/src/main/java/io/harness/exception/HelmClientRuntimeException.java
  980-commons/src/main/java/io/harness/exception/BUILD.bazel
  980-commons/src/main/java/io/harness/exception/ExceptionUtils.java
Labels: cd-kubernetes, cd-deployments

#56663 feat:[CDS-84547]: Harness Store Support for Serverless Aws Lambda and Values Manifest
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestsStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessDownloadManifestV2StepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelperTest.java
Labels: cd-deployments, cd-serverlessV2

#56739 fix: [CDS-86744]: Improved Asg logs
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenPrepareRollbackCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgShiftTrafficCommandTaskHandler.java
Labels: cd-deployments, cd-asg

#56603 techdebt: [CDS-86588]: Clean up oci helm ecr config support ff
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge, cd-kubernetes, cd-deployments

#56315 techdebt: [CDS-85986]: Remove CDS_BASIC_ASG from code
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge, cd-deployments, cd-asg

#56775 feat:[CDS-84546]: Harness Store Support for SAM Directory and Values Manifest
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestsStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/AwsSamDownloadManifestsStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/sam/AwsSamStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessDownloadManifestV2StepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestStepHelperTest.java
Labels: cd-deployments, cd-sam

#56637 techdebt: [CDS-86393]: Clean up ecs basic deployment strategy
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
Labels: do-not-merge, cd-deployments, cd-ecs

#56617 fix:[CDS-85856]: Update instanceSyncPerpetualTaskInfoDTO when helm chart info is updated
  126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
  126-instance/src/main/java/io/harness/service/instancesynchandler/AbstractInstanceSyncHandler.java
  126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
  126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceImplTest.java
  126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java
  126-instance/src/test/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandlerTest.java
Labels: cd-kubernetes, cd-deployments

#56911 fix:[CDS-82267]: print Yaml validation message on the execution log
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
Labels: cd-deployments, cd-pcf

#56954 fix:[CDS-85401]: supporting folders for optimised fetch
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/git/GitFetchFilesConfig.java
Labels: cd-deployments, cd-pcf

#56960 fix: [CDS-71610]: add hint and explanation for kerberos authentication
  120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java
  980-commons/src/main/java/io/harness/exception/ExplanationException.java
  980-commons/src/main/java/io/harness/exception/HintException.java
Labels: cd-deployments, cd-winrm

#57015 feat: [CDS-87189]: updated dtos for ssh aws infra
  125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2Test.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/AwsInstanceFilter.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/SshWinRmAwsInfrastructure.java
Labels: cd-deployments

#56905 fix: [PL-43575]: Regions updated as per google documentation
  890-sm-delegate/src/main/java/io/harness/helpers/ext/gcp/GcpRegion.java
Labels: pl

#56923 feat: [CI-10273] Added the support of dynamic timeout for keys in redis stream
  product/log-service/handler/stream.go
  product/log-service/stream/memory/memory.go
  product/log-service/stream/memory/memory_test.go
  product/log-service/stream/redis/redis.go
  product/log-service/stream/redis/redis_test.go
  product/log-service/stream/stream.go
Labels: go

#56969 feat: [CDS-85485]: Divide sdk response events among multiple redis st…
  953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/PipelineSdkRedisEventsConfig.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/PmsSdkCoreEventsFrameworkConstants.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/PmsSdkCoreEventsFrameworkModule.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisher.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisherTest.java
  pipeline-service/config/config.yml
  pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkConstants.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkModule.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkResponseEventMessageListener.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkResponseEventRedisConsumer.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkResponseSpawnEventMessageListener.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkResponseSpawnEventRedisConsumer.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkStepResponseEventMessageListener.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response/SdkStepResponseEventRedisConsumer.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/execution/consumers/SdkResponseEventMessageListenerTest.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/execution/consumers/SdkResponseEventRedisConsumerTest.java
  pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/events/sdk_response_event.proto
  pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java
  pipeline-service/service/src/main/java/io/harness/PipelineServiceConsumersConfig.java
  pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java
Labels: pipeline

#56694 fix: [PL-42471]: Delegate registration enforced through allowed IPs
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/IPAllowlistResourceUtils.java
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/resource/IpAllowlistApiImpl.java
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/service/IPAllowlistService.java
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/service/impl/IPAllowlistServiceImpl.java
  120-ng-manager/modules/ip-allowlist/src/test/java/io/harness/ipallowlist/resource/IpAllowlistApiImplTest.java
  120-ng-manager/modules/ip-allowlist/src/test/java/io/harness/ipallowlist/service/impl/IPAllowlistServiceImplTest.java
  400-rest/src/main/java/software/wings/app/WingsModule.java
  400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java
  400-rest/src/test/java/software/wings/resources/DelegateAgentResourceTest.java
  930-ng-core-clients/BUILD.bazel
  930-ng-core-clients/src/main/java/io/harness/ipallowlist/IPAllowListClient.java
  930-ng-core-clients/src/main/java/io/harness/ipallowlist/IPAllowListClientModule.java
  930-ng-core-clients/src/main/java/io/harness/ipallowlist/IPAllowListHttpClientFactory.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
  970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java
  990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
  platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupModule.java
Labels: pl

#56716 [feat]: [CDS-82479]: adding TrafficRouting step with related logic
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncExecutableTaskHelper.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncExecutable.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/K8sTrafficRoutingStepVariableCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/instance/util/InstanceSyncStepResolver.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingBaseStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepNode.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/AbstractK8sTrafficRouting.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/ConfigK8sTrafficRouting.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/DefaultK8sTrafficRouting.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/InheritK8sTrafficRouting.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRouting.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingDestination.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingRoute.java
  125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java
  125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/CDStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/K8sTrafficRoutingStepInfoVisitorHelper.java
  125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java
  125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/K8sTrafficRoutingStepVariableCreatorTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/executables/AsyncExecutableTaskHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/executables/CdAsyncExecutableTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelperTest.java
  125-cd-nextgen/src/test/resources/cdng/variables/pipelineWithK8sTrafficRoutingStep.json
  125-cd-nextgen/src/test/resources/recaster/alias/alias.txt
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/v1/YamlTypesV1.java
  127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java
  127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java
  127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/v1/StepSpecTypeConstantsV1.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sTrafficRoutingRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sTrafficRoutingResponse.java
Labels: cd-kubernetes, cd-deployments

#56998 feat: [CDS-86039]: add anonymous credential type to credential DTO
  260-delegate/src/test/resources/kryo-registrations.txt
  400-rest/src/test/resources/manager-kryo-registrations.txt
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/githubconnector/GitHubAnonymous.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/githubconnector/GithubDTOToEntity.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/githubconnector/GithubEntityToDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github/GithubAnonymousDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github/GithubConnectorConstants.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github/GithubHttpAuthenticationType.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github/GithubHttpCredentialsSpecDTO.java
  954-connector-beans/src/main/java/io/harness/serializer/kryo/ConnectorBeansKryoRegistrar.java
Labels: cd-deployments

#56917 fix: [CDS-87011]: Remove helm output of deps update for apply step
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java
Labels: cd-kubernetes, cd-deployments

#57051 feat: [CDS-87190]: adjusted VPC list api call
  120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java
  120-ng-manager/src/test/java/io/harness/ng/core/aws/resources/AwsHelperResourceTest.java
Labels: cd-deployments, cd-winrm, cd-ssh, L1-Reviewed

#56989 techdebt: [CDS-87212]: clean up eks add regional param flag
  126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
  126-instance/src/main/java/io/harness/service/instancesynchandler/NativeHelmInstanceSyncHandler.java
  126-instance/src/test/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandlerTest.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-kubernetes, cd-deployments, cd-ecs

#57022 techdebt: [CDS-81317]: Remove CDS_K8S_EKS_LIST_CLUSTERS_ADD_REGION fr…
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-kubernetes, cd-deployments, cd-ecs

#56761 techdebt: [CDS-86668]: Clean up Github authentication app FF
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
  440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/ScmConnectorValidationParamsProvider.java
  440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java
  440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GithubConnectorValidator.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-deployments

#56596 techdebt: [CDS-74149]: Remove CDS_AZURE_WEBAPP_NG_LISTING_APP_NAMES_AND_SLOTS from code
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge, cd-deployments, cd-webapp

#56950 fix:[CDS-86513]: adding retry logic for clone command
  960-api-services/src/main/java/io/harness/git/GitClientHelper.java
  960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
  960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java
Labels: cd-kubernetes, cd-deployments

#57009 fix: [CDS-84745]: Remove check for task type and fix task timeout
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/task/HelmChartManifestTaskHandler.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/steps/task/HelmChartManifestTaskHandlerTest.java
Labels: cd-kubernetes, cd-deployments

#57036 techdebt: [CDS-86398]: Remove CDS_ENABLE_TRIGGER_YAML_VALIDATION from…
  pipeline-service/modules/ng-triggers/src/main/java/io/harness/NGTriggersModule.java
  pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/NGTriggerYamlSchemaService.java
  pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
  pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerYamlSchemaServiceImpl.java
  pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/service/NGTriggerServiceImplTest.java
  pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/service/NGTriggerYamlSchemaServiceTest.java
Labels: pipeline

#57078 feat: [CDS-87194]: adjusted ssh aws infra host filtering
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfrastructureOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsASGDelegateTaskHelper.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsASGDelegateTaskHelperTest.java
Labels: cd-deployments, cd-winrm, cd-ssh

#56958 fix: [CDS-86051]: ngmanager side changes for GAR and k8s and helm flows
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/googleartifactregistry/service/GARResourceServiceImpl.java
  125-cd-nextgen/src/main/java/io/harness/cdng/buckets/resources/service/GcsResourceServiceImpl.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/gcp/service/impl/GcpResourceServiceImpl.java
  125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/artifact/resources/gar/service/GarResourceServiceImplTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/buckets/resources/service/GcsResourceServiceImplTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/resources/gcp/service/impl/GcpResourceServiceImplTest.java
  127-cd-nextgen-entities/BUILD.bazel
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/gcp/GcpCapabilityHelper.java
Labels: cd-kubernetes, cd-deployments

#57052 [feat]: [CDS-87357]: removing usage of CDS_HELM_SEND_TASK_PROGRESS_NG FF from manager and delegate
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmDeployStepTest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-kubernetes, cd-deployments

#57046 feat: [CDS-86005] Add logic for saving K8s Traffic Routing Metadata in Release
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreator.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorTest.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/TrafficRoutingInfoDTO.java
  960-api-services/src/test/java/io/harness/k8s/releasehistory/K8sLegacyReleaseHistoryTest.java
  960-api-services/src/test/java/io/harness/k8s/releasehistory/K8sReleaseTest.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
  970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java
  970-api-services-beans/src/test/resources/deploy-missing-version.yaml
Labels: cd-kubernetes, cd-deployments

#57062 fix: [CDS-87033]: add executor service to delegate's local SCM server
  260-delegate/BUILD.bazel
  260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
  440-connector-nextgen/src/main/java/io/harness/connector/ConnectorModule.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientConstants.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientImpl.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmLinuxManager.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmMacOSManager.java
  960-api-services/src/main/java/io/harness/helm/BUILD.bazel
  960-api-services/src/main/java/io/harness/helm/HelmCliExecutorFactory.java
  980-commons/src/main/java/io/harness/utils/system/BUILD.bazel
  980-commons/src/main/java/io/harness/utils/system/SystemWrapper.java
Labels: cd-kubernetes, cd-deployments

#57087 feat: [CDS-87409]: adjusted ssh instance sync with aws infra changes
  120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java
  126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/aws/AwsSshWinrmInstanceSyncPerpetualTaskHandler.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfraMapping.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/SshWinRmAwsInfrastructure.java
Labels: cd-winrm, cd-ssh

#57086 fix: [CDS-87279]: add error handling for scm fetch file flow by commi…
  930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/git/ScmFetchFilesHelperNGTest.java
Labels: cd-deployments

#57083 feat: [CDS-82614] Add logic for Traffic Routing in K8s BG swap step [delegate]
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactoryTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorTest.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerService.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/TrafficRoutingInfoDTO.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionExplanation.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java
Labels: cd-kubernetes, cd-deployments

#57118 [feat]: [CDS-86007]: adding traffic routing delegate task logic for config option
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepParametersCommandUnitsTest.java
  260-delegate/src/test/resources/kryo-registrations.txt
  400-rest/src/test/resources/manager-kryo-registrations.txt
  930-delegate-tasks/BUILD.bazel
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreator.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorTest.java
  950-delegate-tasks-beans/BUILD.bazel
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sTrafficRoutingRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sTrafficRoutingResponse.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
  950-delegate-tasks-beans/src/test/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfigTest.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/BUILD.bazel
  960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
  960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
  960-api-services/src/main/java/io/harness/k8s/trafficrouting/BUILD.bazel
  960-api-services/src/main/java/io/harness/k8s/trafficrouting/TrafficRoutingInfoDTO.java
  960-api-services/src/test/java/io/harness/k8s/releasehistory/K8sLegacyReleaseHistoryTest.java
  960-api-services/src/test/java/io/harness/k8s/releasehistory/K8sReleaseTest.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionExplanation.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionMessages.java
  delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java
Labels: cd-kubernetes, cd-deployments
