Repository harness/harness-core, pull requests merged in 2023-11, with the labels that each got.

#54884 fix: [CI-10196]: Do not skip UploadCg when CG is empty
  product/ci/addon/tasks/ti_helper.go
  product/ci/engine/grpc/tiproxy_handler.go
Labels: go

#54891 fix: [CI-10196]: Fix empty CG deserialization error
  product/ci/engine/grpc/tiproxy_handler.go
Labels: go

#54910 [feat]: [CDS-83317]: Used Metadata Call for setupUsages.
  127-cd-nextgen-entities/src/main/java/io/harness/setupusage/InfrastructureEntitySetupUsageHelper.java
  127-cd-nextgen-entities/src/test/java/io/harness/setupusage/InfrastructureEntitySetupUsageHelperTest.java
Labels: do-not-merge

#54919 [feat]: [CDS-83271]: Include and populate the default, allowed-values and execution keywords values in the inputs-metadata api
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java
  953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java
  953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/InputDetails.java
  953-yaml-commons/src/test/java/io/harness/yaml/schema/inputs/YamlInputUtilsTest.java
  pipeline-service/contracts/openapi/v1/openapi.yaml
  pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java
Labels: yaml-simpl

#55066 fix: [CI-10259]: Make test report path optional if args is empty
  commons/go/lib/utils/utils.go
  product/ci/addon/tasks/runtests.go
  product/ci/addon/testintelligence/python/pytest.go
  product/ci/addon/testintelligence/python/unittest.go
  product/ci/addon/testintelligence/ruby/BUILD.bazel
  product/ci/addon/testintelligence/ruby/helper.go
  product/ci/addon/testintelligence/ruby/rspec.go
Labels: go

#55087 fix:[PL-32651]: If ACL Processing is enabled through outbox framework, disable it via Debezium.
  access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java
  access-control/libs/aggregator/src/main/java/io/harness/aggregator/controllers/AggregatorBaseSyncController.java
  access-control/libs/aggregator/src/main/java/io/harness/aggregator/controllers/AggregatorPrimarySyncController.java
  access-control/libs/aggregator/src/main/java/io/harness/aggregator/controllers/AggregatorSecondarySyncController.java
  access-control/libs/aggregator/src/test/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumerTest.java
Labels: pl

#55111 feat:[PL-32650]: In Role assignment outbox handler, setting role assignment UUID for ACL processing.
  access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumer.java
  access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java
Labels: pl

#55096 fix:[PL-42146]: Changing default batch size for ACL creation to 5000.
  access-control/config/config.yml
Labels: pl

#55275 feat: [PL-42486]: Fetch default configs from platform service to send async emails for saas
  platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources/EmailResource.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/resources/EmailResourceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java
Labels: pl

#55320 fix: [CI-10318]: UT fix for log service client
  product/ci/engine/grpc/logproxy_handler_test.go
Labels: go

#55057 feat: [SSCA-838]: populate ssca service secrets on container step group initialization
  332-ci-manager/service/src/main/java/io/harness/ci/execution/plugin/CiPluginStepInfoProvider.java
  332-ci-manager/service/src/test/java/io/harness/ci/plugin/CiPluginStepInfoProviderTest.java
Labels: draft

#55036 feat: [SSCA-887]: remove ssca steps from pipeline service
  332-ssca/cd/src/main/java/io/harness/ssca/cd/CdSscaBeansRegistrar.java
  pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java
Labels: draft

#55355 techdebt: [CDS-84450]: code cleanup for FF GITOPS_FLUX_FLAMINGO
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: java

#55313 feat: [CDS-82999]: added ASGShiftTraffic delegate logic
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgShiftTrafficStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgShiftTrafficStepTest.java
  260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
  260-delegate/src/test/resources/kryo-registrations.txt
  400-rest/src/test/resources/manager-kryo-registrations.txt
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenDeployCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenPrepareRollbackCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgShiftTrafficCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgShiftTrafficTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgTaskHelper.java
  930-delegate-tasks/src/test/java/io/harness/delegate/aws/asg/AsgBlueGreenDeployCommandTaskHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/aws/asg/AsgBlueGreenPrepareRollbackCommandTaskHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/aws/asg/AsgBlueGreenRollbackCommandTaskHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/aws/asg/AsgShiftTrafficCommandTaskHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/asg/AsgTaskHelperTest.java
  950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
  960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java
  960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgConfigurationManifestHandler.java
  960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgManifestHandlerChainFactory.java
  960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgManifestType.java
  960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgShiftTrafficHandler.java
  960-api-services/src/main/java/io/harness/aws/asg/manifest/request/AsgShiftTrafficManifestRequest.java
  960-api-services/src/test/java/io/harness/aws/asg/AsgSdkManagerTest.java
Labels: cd-asg

#55426 fix:[CDS-82777]: Fixed orphaned winrshost.exe process due to stale sessions left
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/winrm/WinRmExecutorHelperTest.java
Labels: cd-deployments, cd-winrm

#55484 fix: [PL-42509]: Added expiry for secret created via heartbeat check of azure key vault
  890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java
  890-sm-delegate/src/test/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandlerTest.java
Labels: pl

#55378 feat:[SSCA-883]: Added Integration with PMS for SLSA and PMS MetaData
  .gitleaksignore
  970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java
  clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java
  ssca-manager/build/container/scripts/replace_configs.sh
  ssca-manager/config/ssca-manager-config.yml
  ssca-manager/contracts/openapi/v1/openapi.yaml
  ssca-manager/service/BUILD.bazel
  ssca-manager/service/src/main/java/io/harness/SSCAManagerConfiguration.java
  ssca-manager/service/src/main/java/io/harness/SSCAManagerModule.java
  ssca-manager/service/src/main/java/io/harness/ssca/beans/PipelineExecutionSummary.java
  ssca-manager/service/src/main/java/io/harness/ssca/beans/SLSAVerificationSummary.java
  ssca-manager/service/src/main/java/io/harness/ssca/entities/CdInstanceSummary.java
  ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java
  ssca-manager/service/src/main/java/io/harness/ssca/services/CdInstanceSummaryService.java
  ssca-manager/service/src/main/java/io/harness/ssca/services/CdInstanceSummaryServiceImpl.java
  ssca-manager/service/src/test/java/io/harness/BuilderFactory.java
  ssca-manager/service/src/test/java/io/harness/SSCAManagerTestRule.java
  ssca-manager/service/src/test/java/io/harness/ssca/services/CdInstanceSummaryServiceImplTest.java
  ssca-manager/service/src/test/resources/pms-execution-response-with-slsa.json
  ssca-manager/service/src/test/resources/pms-execution-response-with-uncorrelated-slsa.json
  ssca-manager/service/src/test/resources/pms-execution-response-without-slsa.json
Labels: draft

#55628 feat:[CDS-84744]: Reversing the events for delete stack step
  960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java
Labels: cd-deployments, cd-cloudformation

#55499 fix: [CDS-84373]: Checkout branch or ref before checkout file paths
  932-connector-task/src/main/java/io/harness/connector/service/git/NGGitServiceImpl.java
  932-connector-task/src/test/java/io/harness/connector/service/git/NGGitServiceImplTest.java
  960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
  960-api-services/src/test/java/io/harness/git/GitClientV2ImplTest.java
  970-api-services-beans/src/main/java/io/harness/git/model/FetchFilesByPathRequest.java
Labels: cd-kubernetes, cd-deployments

#55589 fix: [CDS-84495]: CG Checkout branch or ref before checkout file paths
  930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java
  930-delegate-tasks/src/main/java/software/wings/service/impl/yaml/GitClientImpl.java
  930-delegate-tasks/src/test/java/software/wings/service/impl/GitServiceImplTest.java
  950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java
Labels: cd-kubernetes, cd-deployments

#55665 fix: [CDS-83828] Improve error handling for rendering of helm chart
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmDeployServiceImplNGTest.java
  970-api-services-beans/src/main/java/io/harness/k8s/manifest/ManifestHelper.java
  970-api-services-beans/src/test/java/io/harness/k8s/manifest/ManifestHelperTest.java
Labels: cd-kubernetes, cd-deployments

#55667 fix: [CDS-84389]: added support to Asg infrastructure to resolve exec…
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenRollbackStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgCanaryDeleteStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgRollingRollbackStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgShiftTrafficStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgBlueGreenRollbackStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgCanaryDeleteStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgRollingRollbackStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgShiftTrafficStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgStepCommonHelperTest.java
Labels: cd-deployments, cd-asg

#55518 fix: [CDS-83305]:adding index.yaml size logs if greater than 20mb
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java
  970-api-services-beans/src/main/java/io/harness/helm/HelmConstants.java
  990-commons-test/BUILD.bazel
  990-commons-test/src/main/java/io/harness/LoggerRule.java
Labels: cd-kubernetes, cd-deployments

#55806 feat: [CDS-82817]: FF added for Artifact bundle support in TAS deployment
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-deployments

#55679 feat: [CDS-81422]: cds-aws-backoff-strategy cleanup
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge

#55533 feat: [CDS-82817]: Delegate side changes: Adding new delegate task for Artifact bundle support in TAS deployment
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ArtifactBundleStore.java
  260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchTask.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchTaskHelper.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/artifactbundle/ArtifactBundleFetchTaskHelperTest.java
  930-delegate-tasks/src/test/resources/task/artifactbundle/artifactBundle.tar
  930-delegate-tasks/src/test/resources/task/artifactbundle/artifactBundleGz.tar.gz
  930-delegate-tasks/src/test/resources/task/artifactbundle/artifactBundleZip.zip
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundledArtifactType.java
  951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
  scripts/jenkins/copyright-check.sh
Labels: cd-deployments

#55114 feat: [CDS-83055]: Integrate rancher delete token API
  260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskExecutor.java
  260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
  260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncV2Helper.java
  260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskExcecutor.java
  260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskV2Executor.java
  260-delegate/src/test/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskExecutorTest.java
  260-delegate/src/test/java/io/harness/perpetualtask/K8sInstanceSyncV2HelperTest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/request/BUILD.bazel
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/request/K8sRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/utils/K8sTaskCleaner.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sngtask/K8sTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/rancher/RancherHelper.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmCommandTaskNGTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmDeployServiceImplNGTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskNGTest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/HelmTaskDTO.java
Labels: cd-kubernetes, cd-deployments

#55835 feat: [CDS-83447]: added instance sync support to Asg ShiftTraffic step
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgShiftTrafficStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgShiftTrafficStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/aws/asg/AsgStepCommonHelperTest.java
Labels: cd-deployments, cd-asg

#55903 fix: [CDS-82520] fix bug for K8sDryRunManifestStepV2 step
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sDryRunManifestStepV2.java
Labels: cd-kubernetes, cd-deployments

#55934 fix: [CDS-85374]: adding logic to handle manifest source file paths as expressions
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sApplyStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java
Labels: cd-kubernetes, cd-deployments

#55915 feat:[CDS-84744]: Fix for repeated logs due to reversing the list
  960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java
  960-api-services/src/main/java/io/harness/aws/AwsCloudformationPrintHelper.java
Labels: cd-deployments, cd-cloudformation

#55951 feat: [CDS-83011]: added execution strategy Yaml for Asg Shift Traffi…
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java
  125-cd-nextgen/src/main/resources/executionStrategyYaml/asg-bluegreen-shift-traffic-with-verify.yaml
  125-cd-nextgen/src/main/resources/executionStrategyYaml/asg-bluegreen-shift-traffic.yaml
  125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelperTest.java
  125-cd-nextgen/src/test/resources/executionStrategyYaml/asg-bluegreen-shift-traffic.yaml
  125-cd-nextgen/src/test/resources/executionStrategyYaml/asg-bluegreen.yaml
  878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyParameters.java
Labels: cd-asg

#55861 feat:[CDS-83746]: Harness Runtime Expressions to resolve for all Serverless V2 Steps
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaPackageV2PluginInfoProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessPrepareRollbackPluginInfoProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessRollbackV2PluginInfoProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2StepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2Step.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2StepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPrepareRollbackV2Step.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPrepareRollbackV2StepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaRollbackV2Step.java
  125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaRollbackV2StepInfo.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProviderTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaPackageV2PluginInfoProviderTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaRollbackV2PluginInfoProviderTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessPrepareRollbackPluginInfoProviderTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelperTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployStepV2Test.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageStepV2Test.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPrepareRollbackV2StepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaRollbackV2StepTest.java
Labels: cd-deployments, cd-serverlessV2

#55825 feat: [CDS-82478] Add traffic routing to K8s BG Deploy step
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenBaseStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStepInfo.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStepParameters.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHeaderRuleSpec.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingRule.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sBlueGreenStepTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelperTest.java
  260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
  260-delegate/src/test/resources/kryo-registrations.txt
  400-rest/src/test/java/software/wings/beans/delegation/TaskTypeTest.java
  400-rest/src/test/resources/manager-kryo-registrations.txt
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployRequest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/HeaderConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/IstioProviderConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/MatchType.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/ProviderType.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/RouteType.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/RuleType.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/SMIProviderConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/TrafficRoute.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/TrafficRouteRule.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/TrafficRoutingDestination.java
  950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
  951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
  delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java
Labels: cd-kubernetes, cd-deployments

#55976 fix: [CDS-85428]: resolve dynamic prov expressions in EKS region param
  125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureProvisionerHelper.java
Labels: cd-kubernetes, cd-deployments

#55362 [feat]: [CDS-81940]: adding deployment stage plan creator for v1 schema and r…
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageConfigV1.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerUtils.java
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/StagePlanCreatorHelper.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStagePlanCreator.java
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/StepParametersUtils.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStagePlanCreatorTest.java
  125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerUtilsTest.java
  125-cd-nextgen/src/test/resources/cdng/creator/servicePlanCreator/v1/pipeline.yaml
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/PlanCreatorUtilsV1Test.java
Labels: cd-deployments

#55996 fix:[CDS-85454]: Removed HELM_COMMAND_TASK_NG_JOBS_STEADY_STATE_CHECK task type from manager.
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/helm/NativeHelmStepHelperTest.java
Labels: cd-kubernetes, cd-deployments

#55987 feat: [CDS-79877] Warn user if templates folder is missing during helm template
  960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
Labels: cd-kubernetes, cd-deployments

#55940 feat: [CDS-83173] Upgrade go-template to v0.4.5 for immutable delegate
  dockerization/delegate/Dockerfile
  dockerization/delegate/Dockerfile-ubuntu
Labels: cd-kubernetes, cd-deployments

#55952 feat: [CDS-83782]: PCF support BG only with 2 apps
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasSwapRollbackStep.java
  930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/AppRenamingOperator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/RollbackBGNonVersionToNonVersion.java
  930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfSwapRollbackCommandTaskHandlerNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/cf/CfCommandTaskHelperNG.java
  930-delegate-tasks/src/test/java/io/harness/delegate/pcf/CfSwapRollbackCommandTaskHandlerTest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/pcf/CfRouteUpdateRequestConfigData.java
  951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
Labels: cd-deployments, cd-pcf

#56067 fix: [CDS-85374]: missed logic to add expression handler in case of Git
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/AbstractK8sStepExecutorTestBase.java
  125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sApplyStepTest.java
Labels: cd-kubernetes, cd-deployments

#55945 fix:[CDS-84663]: Storing primaryManifestId in sweeping output
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/steps/ManifestsStepV2Test.java
  125-cd-nextgen/src/test/resources/recaster/alias/alias.txt
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifestConfigs/outcome/ManifestConfigurationsOutcome.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java
  127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
Labels: cd-kubernetes, cd-deployments

#56066 fix: [CDS-83821]: fixed rollback for ASG when instance refresh is in …
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingDeployCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingRollbackCommandTaskHandler.java
  930-delegate-tasks/src/test/java/io/harness/delegate/aws/asg/AsgRollingRollbackCommandTaskHandlerTest.java
  960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java
  960-api-services/src/test/java/io/harness/aws/asg/AsgSdkManagerTest.java
Labels: cd-deployments, cd-asg

#56070 feat: [CDS-83039] Suggest hint to remove templates from the path when specifying helm chart
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java
Labels: cd-kubernetes, cd-deployments

#56111 fix: [CDS-81266]: Add check for NULL values in join for accounts overview query
  120-ng-manager/src/main/resources/timescale/get_active_services_by_date_function_timescale.sql
  125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java
  125-cd-nextgen/src/test/java/io/harness/cdng/usage/CDLicenseUsageDALTest.java
  build.properties
Labels: cds-licensing

#55997 [feat]: [CDS-83036]: adding a kubectl cli auth hint for K8s auth errors
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesApiExceptionHandler.java
  930-delegate-tasks/src/test/java/io/harness/delegate/exceptionhandler/handler/KubernetesApiExceptionHandlerTest.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java
Labels: cd-kubernetes, cd-deployments

#56117 feat: [CDS-82975]: Override and Override validation changes for Artifact Bundle in Tas Maifest
  125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
  125-cd-nextgen/src/test/java/io/harness/cdng/tas/TasStepHelperTest.java
Labels: cd-deployments, cd-pcf
