Repository harness/harness-core, pull requests merged in 2023-08, with the labels that each got.

#51186 fix: [CI-9053]: fix test as source
  product/ci/addon/parser/cg/cg_parser.go
  product/ci/addon/parser/cg/cg_parser_test.go
  product/ci/addon/parser/cg/testdata/cg.json
Labels: go

#50964 [feat]: [CDS-74329]: Integrated live search with list branches and list repos
  952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java
  WORKSPACE
  product/ci/scm/git/git.go
  product/ci/scm/git/git_test.go
  product/ci/scm/git/testdata/repos.json
  product/ci/scm/go.mod
  product/ci/scm/go.sum
Labels: go

#51118 fix: [PL-40352]: fix the InvalidReferenceException in prod env
  platform-service/modules/notification-service/src/main/resources/templates/email_notify.txt
Labels: pl

#50970 feat: [PL-39821]: added config for enabling/disabling cache in hashicorp vault config
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/VaultDTOToEntity.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/VaultEntityToDTO.java
  440-connector-nextgen/src/test/resources/schema/Connectors/all.json
  890-sm-delegate/src/main/java/io/harness/ng/VaultConfigDTOMapper.java
  931-secret-providers/src/java/io/harness/mappers/VaultConfigMapper.java
  931-secret-providers/src/java/software/wings/beans/BaseVaultConfig.java
  940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/VaultConfigDTO.java
  940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/VaultConfigUpdateDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/outcome/VaultConnectorOutcomeDTO.java
  970-ng-commons/src/main/java/io/harness/SecretManagerDescriptionConstants.java
Labels: pl

#50465 fix: [PL-38979]: Call service layer instead of direct delete
  400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/test/java/software/wings/security/authentication/SamlBasedAuthHandlerTest.java
Labels: pl

#51275 fix: [PL-40064]: fix client call to delete membership
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
Labels: pl

#51136 feat: [PL-39761]: added new EULA svc to sign different user agreements
  120-ng-manager/BUILD.bazel
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/AgreementType.java
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/BUILD.bazel
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/dto/BUILD.bazel
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/dto/EulaDTO.java
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/entity/BUILD.bazel
  120-ng-manager/modules/eula/contracts/src/main/java/io/harness/eula/entity/Eula.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/events/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/events/EulaSignEvent.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/mapper/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/mapper/EulaMapper.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/outbox/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/outbox/EulaEventHandler.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/resource/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/resource/EulaApiImpl.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/service/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/service/EulaService.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/service/impl/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/service/impl/EulaServiceImpl.java
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/utils/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/eula/utils/EulaResourceUtils.java
  120-ng-manager/modules/eula/src/main/java/io/harness/repositories/eula/custom/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/repositories/eula/custom/EulaRepositoryCustom.java
  120-ng-manager/modules/eula/src/main/java/io/harness/repositories/eula/custom/EulaRepositoryCustomImpl.java
  120-ng-manager/modules/eula/src/main/java/io/harness/repositories/eula/spring/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/repositories/eula/spring/EulaRepository.java
  120-ng-manager/modules/eula/src/main/java/io/harness/serializer/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/serializer/EulaRegistrar.java
  120-ng-manager/modules/eula/src/main/java/io/harness/serializer/morphia/BUILD.bazel
  120-ng-manager/modules/eula/src/main/java/io/harness/serializer/morphia/EulaMorphiaRegistrar.java
  120-ng-manager/modules/eula/src/test/java/io/harness/eula/mapper/BUILD.bazel
  120-ng-manager/modules/eula/src/test/java/io/harness/eula/mapper/EulaMapperTest.java
  120-ng-manager/modules/eula/src/test/java/io/harness/eula/service/impl/BUILD.bazel
  120-ng-manager/modules/eula/src/test/java/io/harness/eula/service/impl/EulaServiceImplTest.java
  120-ng-manager/src/main/java/io/harness/ng/EulaModule.java
  120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java
  120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java
  120-ng-manager/src/main/java/io/harness/serializer/NextGenRegistrars.java
  120-ng-manager/src/test/resources/mongo/indexes.txt
  platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java
  platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceType.java
  platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java
  platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
Labels: pl

#51424 fix: [PL-40547]: Improve manual websocket reconnect for longer outages
  260-delegate/src/main/java/io/harness/delegate/logging/DelegateStackdriverLogAppender.java
  260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
  980-commons/src/main/java/io/harness/network/FibonacciBackOff.java
Labels: pl

#51425 fix: [PL-40547]: Improve manual websocket reconnect for longer outages
  260-delegate/build.properties
  260-delegate/src/main/java/io/harness/delegate/logging/DelegateStackdriverLogAppender.java
  260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
  980-commons/src/main/java/io/harness/network/FibonacciBackOff.java
Labels: pl

#50471 feat: [PL-39821]: add cache for hashicorp vault app role token
  890-sm-delegate/src/main/java/io/harness/delegatetasks/NGVaultFetchEngineTask.java
  930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java
  931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java
  931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java
  931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java
  931-vault-beans/src/java/io/harness/helpers/vault/NGVaultTaskHelper.java
  931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel
  931-vault-beans/src/test/io/harness/helpers/vault/HashicorpVaultTokenCacheHelperTest.java
Labels: pl

#51011 fix: [CI-8904]: Add retries when calling SCM APIs
  product/ci/scm/git/git.go
  product/ci/scm/git/git_test.go
Labels: go

#51530 feat: [PL-31131]: Added log to indicate Deduping of user group event.
  access-control/service/src/main/java/io/harness/accesscontrol/principals/usergroups/HarnessUserGroupServiceImpl.java
Labels: pl

#51214 feat: [PL-39761]: added AIDA setting and validator
  120-ng-manager/modules/ng-settings/BUILD.bazel
  120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java
  120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifiers.java
  120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java
  120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/EnableAidaValidator.java
  120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
  120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/EnableAidaValidatorTest.java
Labels: pl

#51035 fix: [PL-40007]: Send cause of notification failure.
  930-delegate-tasks/src/main/java/io/harness/notification/senders/MailSenderImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java
Labels: pl

#51531 fix: [PL-39762]: Add context to ResourceGroup Async Reconciliation to avoid getting access control error
  platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/reconciliation/ResourceGroupAsyncReconciliationHandler.java
Labels: pl

#51440 feat: [CDS-70107]: Add when condition in Yaml V1
  953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/test/resources/complex-pipeline-with-group-v1.yaml
  pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java
  pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreatorV1.java
  pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/plancreator/PipelineStagePlanCreatorV1.java
Labels: yaml-simpl

#51905 fix: [PL-40641]: Failed count should not consider deleted streaming destinations
  platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImpl.java
  platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepositoryCustom.java
  platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepositoryCustomImpl.java
  platform-service/modules/audit-service/src/test/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImplTest.java
Labels: pl

#49671 feat: [PL-32647]: Added support for pausing renewal of Vault connectors
  120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java
Labels: pl

#51897 [feat]: [CDS-77315]: Converted null values to empty for Grpc call.
  136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java
  136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
  878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java
  900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java
  900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java
Labels: do-not-merge

#52020 feat: [CDS-77357]: set nodeMetadata in dependency v1 plan creators
  310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreatorV1.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3/IntegrationStagePMSPlanCreatorV3.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java
  879-pipeline-ci-commons/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/DependencyMetadata.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/parallel/v1/ParallelPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/StepsPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/PlanCreatorUtilsV1Test.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/group/GroupPlanCreatorV1Test.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/stages/parallel/v1/ParallelPlanCreatorV1Test.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/StrategyUtilsV1Test.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreatorV1.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/NextStepHandlerTest.java
  pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/plancreator/PipelineStagePlanCreatorV1.java
  pipeline-service/service/src/test/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImplTest.java
  pipeline-service/service/src/test/java/io/harness/pms/pipeline/mappers/GraphLayoutDtoMapperTest.java
Labels: yaml-simpl

#51716 feat: [PL-39275]: Send events to segment for project related audit enteries
  dockerization/platform-service/scripts/replace_configs.sh
  platform-service/config/config.yml
  platform-service/modules/audit-service/BUILD.bazel
  platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
  platform-service/modules/audit-service/src/test/java/io/harness/audit/api/impl/AuditServiceImplTest.java
  platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java
  platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceModule.java
  platform-service/service/src/test/resources/test-config.yml
Labels: pl

#51717 feat: [PL-39275]: Send events to segment for account logins
  400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
Labels: pl

#52151 [fix]: [PL-40706]: Updates error log to warn
  970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java
Labels: pl

#52096 feat: [CI-9117]: Add ruby runner
  WORKSPACE
  commons/go/lib/utils/utils.go
  product/ci/addon/go.mod
  product/ci/addon/go.sum
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/tasks/ti_helper.go
  product/ci/addon/testintelligence/python/pytest.go
  product/ci/addon/testintelligence/python/unittest.go
  product/ci/addon/testintelligence/ruby/BUILD.bazel
  product/ci/addon/testintelligence/ruby/helper.go
  product/ci/addon/testintelligence/ruby/rspec.go
Labels: go

#52186 feat: [PL-39275]: send prometheus event fro active project metrics
  platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
  platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java
  platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java
  platform-service/service/src/main/resources/metrics/metricDefinitions/active_project_metrics.yaml
  platform-service/service/src/main/resources/metrics/metricGroups/active_project_metrics_group.yaml
Labels: pl
