Repository harness/harness-core, pull requests merged in 2023-07, with the labels that each got.

#49706 feat: [PL-39666]: Removing FF ACCOUNT_BASIC_ROLE_ONLY as no longer used.
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl

#50071 fix: [PL-39801]: Add delegate name to DW config to pass parsing
  260-delegate/dw-config-delegate.yml
  260-delegate/src/main/java/io/harness/delegate/app/DelegateAgentConfig.java
Labels: pl

#49536 feat: [CI-7503]: Delegate/manager changes to inject delegate task id in SCM logs
  100-migrator/config.yml
  270-delegate-service-app/delegate-service-config.yml
  270-delegate-service-app/src/test/resources/test-config-delegate-service.yml
  360-cg-manager/config.yml
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmLinuxManager.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmMacOSManager.java
  952-scm-java-client/BUILD.bazel
  952-scm-java-client/src/main/java/io/harness/SCMGrpcClientModule.java
  960-api-services/src/main/java/io/harness/delegate/clienttools/ScmVersion.java
  960-api-services/src/test/java/io/harness/delegate/clienttools/InstallUtilsTest.java
  970-grpc/BUILD.bazel
  970-grpc/src/main/java/io/harness/grpc/client/SCMGrpcInterceptor.java
  dockerization/delegate-proxy/setup.sh
  dockerization/delegate/Dockerfile
  dockerization/delegate/Dockerfile-minimal
  dockerization/delegate/Dockerfile-ubuntu
  dockerization/delegate/scripts/client_tools.sh
Labels: do-not-merge

#49864 fix: [PL-39304]: Fixed the API documentation of variables to update the type
  120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/dto/StringVariableConfigDTO.java
  120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/dto/VariableConfigDTO.java
Labels: pl

#48769 fix: [PL-38776]: Fix pagination in secrets list api in CG.
  890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java
Labels: pl

#50049 feat: [PL-31936]: Allow auto acceptance of users
  400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
  400-rest/src/test/java/software/wings/service/AccountServiceTest.java
Labels: pl

#49758 fix: [PL-38735]: NG reset password emails to go through NG
  160-model-gen-tool/config-datagen.yml
  160-model-gen-tool/src/main/java/io/harness/DataGenApplication.java
  220-graphql-test/src/supporter-test/java/io/harness/rule/GraphQLRule.java
  360-cg-manager/config.yml
  360-cg-manager/src/main/java/software/wings/app/WingsApplication.java
  400-rest/src/main/java/software/wings/app/MainConfiguration.java
  400-rest/src/main/java/software/wings/app/WingsModule.java
  400-rest/src/main/java/software/wings/app/WingsModulePersistenceModule.java
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/supporter-test/java/software/wings/rules/WingsRule.java
  clients/notification/src/main/java/io/harness/notification/module/NotificationClientModule.java
  clients/notification/src/main/java/io/harness/notification/templates/PredefinedTemplate.java
  dockerization/manager/scripts/replace_configs.sh
  platform-service/modules/notification-service/src/main/resources/templates/ng_reset_password.txt
Labels: pl

#50116 feat: [BT-4536]: Adding run_analysis to go modules build files
  commons/go/lib/archive/BUILD.bazel
  commons/go/lib/awsutils/BUILD.bazel
  commons/go/lib/db/BUILD.bazel
  commons/go/lib/delegate-task-grpc-service/grpc/BUILD.bazel
  commons/go/lib/exec/BUILD.bazel
  commons/go/lib/expression-service/grpc/BUILD.bazel
  commons/go/lib/filesystem/BUILD.bazel
  commons/go/lib/gcputils/BUILD.bazel
  commons/go/lib/images/BUILD.bazel
  commons/go/lib/jfrogutils/BUILD.bazel
  commons/go/lib/kaniko/BUILD.bazel
  commons/go/lib/logs/BUILD.bazel
  commons/go/lib/minio/BUILD.bazel
  commons/go/lib/utils/BUILD.bazel
  product/ci/addon/BUILD.bazel
  product/ci/addon/gojunit/BUILD.bazel
  product/ci/addon/grpc/BUILD.bazel
  product/ci/addon/grpc/client/BUILD.bazel
  product/ci/addon/logs/BUILD.bazel
  product/ci/addon/parser/cg/BUILD.bazel
  product/ci/addon/remote/BUILD.bazel
  product/ci/addon/resolver/BUILD.bazel
  product/ci/addon/services/BUILD.bazel
  product/ci/addon/tasks/BUILD.bazel
  product/ci/addon/testintelligence/csharp/BUILD.bazel
  product/ci/addon/testintelligence/java/BUILD.bazel
  product/ci/addon/testreports/junit/BUILD.bazel
  product/ci/common/logs/BUILD.bazel
  product/ci/engine/BUILD.bazel
  product/ci/engine/grpc/BUILD.bazel
  product/ci/engine/grpc/client/BUILD.bazel
  product/ci/engine/legacy/artifacts/BUILD.bazel
  product/ci/engine/legacy/executor/BUILD.bazel
  product/ci/engine/legacy/jexl/BUILD.bazel
  product/ci/engine/legacy/steps/BUILD.bazel
  product/ci/engine/logutil/BUILD.bazel
  product/ci/engine/new/executor/BUILD.bazel
  product/ci/engine/status/BUILD.bazel
  product/ci/scm/BUILD.bazel
  product/ci/scm/converter/BUILD.bazel
  product/ci/scm/file/BUILD.bazel
  product/ci/scm/git/BUILD.bazel
  product/ci/scm/gitclient/BUILD.bazel
  product/ci/scm/grpc/BUILD.bazel
  product/ci/scm/grpc/client/BUILD.bazel
  product/ci/scm/parser/BUILD.bazel
  product/ci/scm/repo/BUILD.bazel
  product/ci/split_tests/BUILD.bazel
  product/log-service/handler/BUILD.bazel
  product/log-service/logger/BUILD.bazel
  product/log-service/store/bolt/BUILD.bazel
  product/log-service/store/s3/BUILD.bazel
  product/log-service/stream/memory/BUILD.bazel
  product/log-service/stream/redis/BUILD.bazel
  queue-service/hsqs/handler/BUILD.bazel
  queue-service/hsqs/middleware/BUILD.bazel
  queue-service/hsqs/store/redis/BUILD.bazel
Labels: go

#50173 fix: [PL-39503]: add validation in RG to check duplicate identifier
  980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java
  platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java
  platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImplTest.java
Labels: pl

#49975 feat: [PL-39278]: Enhancements for activityHistory list API
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/NGActivityQueryCriteriaHelper.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/impl/NGActivityServiceImpl.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/service/NGActivityService.java
  950-ng-core/src/test/java/io/harness/ng/core/activityhistory/impl/NGActivityServiceImplTest.java
  950-ng-core/src/test/java/io/harness/ng/core/activityhistory/resource/NGActivityResourceTest.java
  970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java
Labels: pl

#50205 feat: [PL-39861]: add NO_LIMIT to UsageRestrictionService queries
  400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkMigrationHelper.java
  400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java
  400-rest/src/test/java/software/wings/service/impl/UsageRestrictionsServiceImplTest.java
Labels: pl

#50286 feat: [PL-28392]: changed azure api to fetch vaults list
  890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java
  890-sm-delegate/src/main/java/io/harness/helpers/ext/azure/KeyVaultAuthenticator.java
Labels: pl

#50009 fix: [PL-39271]: Adding default included scope as current scope at which Resource group is created.
  access-control/service/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactory.java
  access-control/service/src/test/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactoryTest.java
  platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
  platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java
Labels: pl

#50573 [fix]: [PL-39990]: update min and max response timeout for NG LDAP delegate task
  120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java
Labels: pl

#50570 [fix]: [PL-39990]: update min and max response timeout for NG LDAP delegate task
  120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java
  120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java
Labels: pl

#49956 feat: [PL-39616]: add admin API to disable IP allowlist for an account
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustom.java
  120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustomImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java
  400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
  400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
  400-rest/src/main/java/software/wings/service/intfc/AccountService.java
  953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java
Labels: pl

#50562 feat: [PL-32544]: Change Redis EventListener in Access control service to have multiples threads process events.
  access-control/config/config.yml
  access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/events/EntityCrudEventListenerService.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/events/EventListenerService.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/events/EventsConfig.java
  access-control/service/src/main/java/io/harness/accesscontrol/commons/events/UserMembershipEventListenerService.java
Labels: pl

#50695 fix: [PL-40013]: fixed sorting order in connector
  440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java
  440-connector-nextgen/src/test/java/io/harness/repositories/ConnectorCustomRepositoryImplTest.java
Labels: pl

#50638 fix: [CDS-74559]: return rancher cluster ID while listing clusters
  930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/rancher/RancherKubeConfigGenerator.java
  960-api-services/src/main/java/io/harness/rancher/RancherClusterClientImpl.java
  960-api-services/src/main/java/io/harness/rancher/RancherConnectionHelperServiceImpl.java
  960-api-services/src/main/java/io/harness/rancher/RancherRestClient.java
  960-api-services/src/test/java/io/harness/rancher/RancherConnectionHelperServiceImplTest.java
Labels: do-not-merge, pending-testing

#50461 techdebt: [PL-39953]: Openhft chronicle-queue library update
  WORKSPACE
  bazelrc.common
  project/main_maven_install.json
Labels: pl

#50329 techdebt: [PL-39896]: Change PL runtime env to java 17
  platform-service/build/container/Dockerfile-platform-service-cie-jdk
Labels: pl

#50817 [fix]: [PL-32585]: Fixed Account Edition Incorrect in Switch Account
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/test/java/software/wings/service/impl/UserServiceImplTest.java
Labels: pl

#51013 feat: [PL-40064]: Add deletion support for userMetaData
  123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java
  123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java
  123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java
  123-ng-core-user/src/main/java/io/harness/repositories/user/spring/UserMetadataRepository.java
  123-ng-core-user/src/test/java/io/harness/ng/core/user/remote/UserResourceTest.java
  400-rest/src/main/java/software/wings/helpers/ext/account/DeleteAccountHelper.java
  400-rest/src/main/java/software/wings/service/impl/UserServiceHelper.java
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/test/java/software/wings/service/UserServiceTest.java
  400-rest/src/test/java/software/wings/service/impl/UserServiceHelperTest.java
  930-ng-core-clients/src/main/java/io/harness/usermembership/remote/UserMembershipClient.java
Labels: pl
