Repository harness/harness-core, pull requests merged in 2023-01, with the labels that each got.

#42072 fix: [CI-6565]: Use one bazel query to find all test rules
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/bazel_test.go
  product/ci/addon/testintelligence/java/helper.go
Labels: go

#42309 feat: [CI-5815]: Parallelism support for Scala/Kotlin with Bazel
  product/ci/addon/testintelligence/java/bazel.go
  product/ci/addon/testintelligence/java/bazel_test.go
Labels: go

#42593 fix: [CI-6700]: Update file package using pointers
  product/ci/addon/tasks/runtests.go
Labels: go

#42667 [fix]: [PIE-7657]: Adding fix for authentication issue with Queue Service
  332-ci-manager/service/src/main/java/io/harness/ci/execution/CIExecutionServiceModule.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/queue/CIExecutionPoller.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java
  400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java
  400-rest/src/test/java/io/harness/delegate/queueservice/DelegateTaskQueueServiceTest.java
  WORKSPACE
  clients/queue-service/java-client/BUILD.bazel
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ApiCallback.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ApiClient.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ApiException.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ApiResponse.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/Configuration.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/GzipRequestInterceptor.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/HsqsServiceClient.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/HsqsServiceClientModule.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/JSON.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/Pair.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ProgressRequestBody.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/ProgressResponseBody.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/StringUtils.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/api/DefaultApi.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/auth/ApiKeyAuth.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/auth/Authentication.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/auth/HttpBasicAuth.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/auth/OAuth.java
  clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/auth/OAuthFlow.java
  pipeline-service/config/config.yml
  pipeline-service/service/BUILD.bazel
  pipeline-service/service/src/main/java/io/harness/PipelineServiceConfiguration.java
  pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java
  project/main_maven_install.json
  queue-service/hsqs/cmd/server.go
  queue-service/hsqs/config/config.go
  queue-service/hsqs/handler/handler.go
  queue-service/hsqs/store/redis/redis_store.go
  queue-service/hsqs/store/redis/redis_store_test.go
  queue-service/hsqs/store/types.go
Labels: go

#42797 fix: [CDS-50989]: improved error message for service runtime access permission
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java
Labels: CDNG

#42944 fix: [CI-6659]: populated link in bitbucket onprem
  product/ci/scm/git/BUILD.bazel
  product/ci/scm/git/git.go
  product/ci/scm/git/git_test.go
  product/ci/scm/git/testdata/commit_bb_onprem.json
Labels: go

#43181 feat: [CCM-10384]: AWS-SMP Data Pipeline and common CH changes
  490-ce-commons/src/main/java/io/harness/ccm/clickHouse/ClickHouseService.java
  490-ce-commons/src/main/java/io/harness/ccm/clickHouse/ClickHouseServiceImpl.java
  490-ce-commons/src/main/java/io/harness/ccm/commons/beans/config/ClickHouseConfig.java
  490-ce-commons/src/main/java/io/harness/ccm/service/impl/AWSBucketPolicyHelperServiceImpl.java
  batch-processing/build/container/scripts/replace_configs.sh
  batch-processing/service/batch-processing-config.yml
  batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java
  batch-processing/service/src/main/java/io/harness/batch/processing/config/BatchMainConfig.java
  batch-processing/service/src/main/java/io/harness/batch/processing/config/BatchProcessingModule.java
  batch-processing/service/src/main/java/io/harness/batch/processing/config/S3ToClickHouseSyncJobConfig.java
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/S3ToClickHouseSyncTasklet.java
  batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/util/ClickHouseConstants.java
  ce-nextgen/build/container/scripts/replace_configs.sh
  ce-nextgen/service/src/main/java/io/harness/ccm/service/impl/AwsEntityChangeEventServiceImpl.java
  dockerization/batch-processing/scripts/replace_configs.sh
  dockerization/ce-nextgen/scripts/replace_configs.sh
Labels: do-not-merge
