Repository harness/harness-core, pull requests merged in 2023-05, with the labels that each got.

#47086 [feat]: [CI-7731]: Improve Junit logging
  product/ci/addon/testreports/junit/junit.go
Labels: gojava

#47572 [fix]: [CI-7586]: Increase character limit when parsing Junit XML
  product/ci/addon/testreports/junit/junit.go
Labels: gojava

#47624 [fix]: [CI-7809]: update python parser
  commons/go/lib/utils/utils.go
Labels: gojava

#47853 [feat]: [CI-8064]: Fix addon and engine docker files
  product/ci/addon/docker/Dockerfile.linux.amd64
  product/ci/addon/docker/Dockerfile.linux.arm64
  product/ci/engine/docker/Dockerfile.linux.amd64
  product/ci/engine/docker/Dockerfile.linux.arm64
  product/log-service/docker/Dockerfile-ubi
Labels: go

#47654 techdebt: [CDS-67768]: Abstracting out common ci code to pipeline-ci-…
  332-ci-manager/service/src/main/java/io/harness/ci/execution/CIExecutionServiceModule.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/PluginSettingUtils.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/IntegrationStageUtils.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/PluginCompatibleStepSerializer.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java
  332-ci-manager/service/src/test/java/io/harness/ci/integrationstage/IntegrationStageUtilsTest.java
  332-ci-manager/service/src/test/java/io/harness/ci/stateutils/buildstate/PluginSettingUtilsTest.java
  879-pipeline-ci-commons/src/main/java/io/harness/ci/executable/CiAsyncExecutable.java
  879-pipeline-ci-commons/src/main/java/io/harness/plugin/GitCloneStep.java
  879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/BasePluginCompatibleSerializer.java
  879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/K8sInitializeService.java
  879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginService.java
  879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginServiceImpl.java
  879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
  879-pipeline-ci-commons/src/main/java/io/harness/utils/CiCodebaseUtils.java
  879-pipeline-ci-commons/src/main/java/io/harness/utils/CiIntegrationStageUtils.java
Labels: do-not-merge

#47779 feat: [CI-8048]: Add support for python for remote debug
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/RunStepProtobufSerializer.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
  332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/vm/VmRunStepSerializer.java
Labels: go

#48123 [fix]: [CI-8064]: Go back to old base image for addon and engine
  product/ci/addon/docker/Dockerfile.linux.amd64
  product/ci/addon/docker/Dockerfile.linux.arm64
  product/ci/engine/docker/Dockerfile.linux.amd64
  product/ci/engine/docker/Dockerfile.linux.arm64
Labels: go

#48181 feat: [PL-38871]: add option to provide delegate selectors in smtp config
  120-ng-manager/src/main/java/io/harness/ng/core/mapper/NgSmtpDTOMapper.java
  120-ng-manager/src/test/java/io/harness/ng/core/mapper/NgSmtpDTOMapperTest.java
  400-rest/src/main/java/software/wings/resources/SmtpConfigResourceNG.java
  930-delegate-tasks/src/main/java/software/wings/helpers/ext/mail/SmtpConfig.java
  950-delegate-tasks-beans/src/main/java/io/harness/notification/SmtpConfig.java
  960-ng-core-beans/src/main/java/io/harness/ng/core/dto/SmtpConfigDTO.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/MailServiceImplTest.java
Labels: enhancement

#48385 [feat]: [CI-7731]: Improve Junit logging
  product/ci/addon/testreports/junit/junit.go
Labels: go

#48491 [fix]: [CI-4977]: Consider all repos safe
  product/ci/common/external/util.go
Labels: go

#48230 feat: [CI-8163]: Log intelligence to predict RCA for failed step
  .github/workflows/no_op_go.yaml
  product/log-service/README.md
  product/log-service/config/config.go
  product/log-service/handler/BUILD.bazel
  product/log-service/handler/genai_client.go
  product/log-service/handler/handler.go
  product/log-service/handler/intelligence.go
Labels: go

#48600 fix: [IDP-590] Add NextGenManagerAuth annotation
  idp-service/src/main/java/io/harness/idp/proxy/delegate/DelegateProxyApiImpl.java
  idp-service/src/main/java/io/harness/idp/proxy/ngmanager/NgManagerProxyApiImpl.java
Labels: pl
