Repository harness/harness-core, pull requests merged in 2023-09, with the labels that each got.

#52301 feat: [CDS-77359]: register new failure strategy with kryoserializer
  332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java
  400-rest/src/test/resources/manager-kryo-registrations.txt
  879-pipeline-ci-commons/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java
  884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java
  953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/v1/NGFailureTypeV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/StepsPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/PlanCreatorUtilsV1Test.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/group/GroupPlanCreatorV1Test.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/stages/parallel/v1/ParallelPlanCreatorV1Test.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/NextStepHandlerTest.java
  pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/plancreator/PipelineStagePlanCreatorV1.java
  pipeline-service/service/src/test/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImplTest.java
  pipeline-service/service/src/test/java/io/harness/pms/pipeline/mappers/GraphLayoutDtoMapperTest.java
Labels: yaml-simpl

#52165 feat: [CDS-77359]: add utils for failure strategies advisors
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java
Labels: yaml-simpl

#52423 feat: [CDS-78707]: added log service improved prompt for CD
  product/log-service/handler/intelligence.go
Labels: go

#52355 feat: [CDS-77359]: add adviser obtainments for failure strategies
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/v1/StrategyConfigPlanCreatorV1Test.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java
Labels: yaml-simpl

#52406 feat: [CDS-78524]: add adviser for retry failure strategy
  400-rest/src/test/resources/manager-kryo-registrations.txt
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ActionConfigPostRetry.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ManualInterventionActionConfigPostRetry.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserRollbackParameters.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java
Labels: yaml-simpl

#51449 [fix]: [PL-28077]: Added Logs for UnknownHost Exception and handled error for LDAP
  120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java
  120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/SocketConnectivityCapabilityCheck.java
Labels: pl

#52564 feat: [CDS-78733]: add adviser for retry step group failure strategy
  953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryFailureSpecConfigV1.java
  953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryStepGroupFailureSpecConfigV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java
  pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java
Labels: yaml-simpl

#52159 [fix]: [PL-40860]: update default cron expression to 1 hour
  160-model-gen-tool/config-datagen.yml
  270-delegate-service-app/delegate-service-config.yml
  360-cg-manager/config.yml
  400-rest/src/test/java/software/wings/service/impl/SSOSettingServiceImplTest.java
Labels: pl

#52732 fix: [CI-9240]: don't add logger if user provided an argument
  product/ci/addon/testintelligence/csharp/dotnet.go
  product/ci/addon/testintelligence/csharp/dotnet_test.go
Labels: go

#52934 [feat]: [CI-8932]: Fix TI for Manual Executions
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
Labels: go

#52959 [fix]: [PL-32454]: suppress the error with pagination, in cases when old logic works
  950-delegate-tasks-beans/src/main/java/software/wings/helpers/ext/ldap/LdapSearch.java
Labels: pl

#52910 [fix]: [CDS-79102]: Saving the service and env identifiers in the pipeline list filters for deployment module instead of service/env names
  125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
  125-cd-nextgen/src/test/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2Test.java
Labels: do-not-merge

#52996 [fix]: [PL-31849]: remove FF PL_ADD_ACL_CHECKS_NG_SCIM_API from BE
  120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java
  120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl

#52760 feat: [PL-40652]: added support for providing custom headers in webhook notification
  930-delegate-tasks/src/main/java/io/harness/delegate/task/webhook/WebhookSenderDelegateTask.java
  930-delegate-tasks/src/main/java/io/harness/notification/senders/WebhookSenderImpl.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/WebhookTaskParams.java
  950-delegate-tasks-beans/src/main/proto/io/harness/notification/notification_request.proto
  clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/WebhookChannel.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/WebhookServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/api/NotificationSettingsService.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/DefaultWebhookServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/WebhookSenderImplTest.java
Labels: pl

#53132 fix: [PL-39331]: update email to lowerCase when signup with OAuth
  920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java
  920-ng-signup/src/test/java/io/harness/signup/services/SignupServiceImplTest.java
  950-ng-signup-beans/src/main/java/io/harness/signup/dto/OAuthSignupDTO.java
Labels: pl

#51715 feat: [PL-39481]: added new notification settings for target domain/url
  120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifiers.java
  120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/service/WebhookServiceImpl.java
  platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/NotificationSettingsHelper.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/DefaultWebhookServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/MSTeamsServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/MailServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/PagerDutyServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/service/SlackServiceImplTest.java
  platform-service/modules/notification-service/src/test/java/io/harness/notification/utils/NotificationSettingsHelperTest.java
Labels: pl

#53129 feat: [CDS-78700] helm improved instance sync tracking
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
  125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
  125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmDeployStepTest.java
  125-cd-nextgen/src/test/resources/recaster/alias/alias.txt
  126-instance/src/main/java/io/harness/dtos/deploymentinfo/NativeHelmDeploymentInfoDTO.java
  126-instance/src/main/java/io/harness/entities/InstanceSyncPerpetualTaskMappingServiceImpl.java
  126-instance/src/main/java/io/harness/entities/deploymentinfo/NativeHelmDeploymentInfo.java
  126-instance/src/main/java/io/harness/helper/K8sAndHelmInfrastructureUtility.java
  126-instance/src/main/java/io/harness/mappers/deploymentinfomapper/NativeHelmDeploymentInfoMapper.java
  126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepository.java
  126-instance/src/main/java/io/harness/service/instancesynchandler/NativeHelmInstanceSyncHandler.java
  126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/helm/NativeHelmInstanceSyncPerpetualTaskHandler.java
  126-instance/src/test/java/io/harness/helper/K8sAndHelmInfrastructureUtilityTest.java
  126-instance/src/test/java/io/harness/mappers/deploymentinfomapper/NativeHelmDeploymentInfoMapperTest.java
  126-instance/src/test/java/io/harness/service/instancesynchandler/NativeHelmInstanceSyncHandlerTest.java
  126-instance/src/test/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/helm/NativeHelmInstanceSyncPerpetualTaskHandlerTest.java
  332-ci-manager/service/src/test/resources/recaster/alias/alias.txt
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/NativeHelmDeploymentOutcomeMetadata.java
  pipeline-service/modules/orchestration-steps/src/test/resources/recaster/alias/alias.txt
  pipeline-service/modules/orchestration-visualization/src/test/resources/recaster/alias/alias.txt
  pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt
  pipeline-service/service/src/test/resources/recaster/alias/alias.txt
Labels: pending-testing

#53190 feat: [CI-9117]: Ruby runner sync with latest agent
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/addon/testintelligence/ruby/helper.go
  product/ci/addon/testintelligence/ruby/rspec.go
Labels: go

#53004 feat:[PL-31244]: Removed FF PL_HIDE_LAUNCH_NEXTGEN.
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl
