Repository harness/harness-core, pull requests merged in 2023-04, with the labels that each got.

#46022 [fix]:[CCM-9930]: added databind dependencies override
  WORKSPACE
  ce-nextgen/service/BUILD.bazel
Labels: cve-vulnerability

#46088 fix: [CDS-58591]: adding k8sOutcome to extract declarative rollback boolean
  125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDeleteStep.java
Labels: pending-testing

#46734 fix: [CI-7800]: Read parallelism env from input map instead of addon env
  product/ci/addon/tasks/runtests.go
  product/ci/addon/tasks/runtests_test.go
  product/ci/common/external/util.go
  product/ci/split_tests/main.go
Labels: go

#46809 fix: [CI-7814]: Use node index/total for split test
  product/ci/split_tests/main.go
Labels: go

#46931 [feat]: [CI-7491]: Fix Output vars for Runtests
  product/ci/addon/tasks/runtests.go
Labels: go

#47020 fix: [CDS-59459]: Handling of multi-service as stage templates
  100-migrator/src/main/java/io/harness/ngmigration/service/workflow/CanaryWorkflowHandlerImpl.java
  100-migrator/src/main/java/io/harness/ngmigration/service/workflow/WorkflowHandler.java
Labels: draft
