Repository harness/harness-core, pull requests merged in 2023-06, with the labels that each got.

#48597 fix: [PL-38953]: Remove Usage of FF ACCOUNT_BASIC_ROLE_ONLY.
  123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java
  123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceTest.java
  access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java
  access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/UserRoleAssignmentRemovalJob.java
  access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigrationTest.java
  access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/worker/UserRoleAssignmentRemovalJobTest.java
Labels: pl

#48643 fix: [CI-8252]: Add authorization for log service to genai service
  WORKSPACE
  product/log-service/config/config.go
  product/log-service/go.mod
  product/log-service/go.sum
  product/log-service/handler/BUILD.bazel
  product/log-service/handler/genai_client.go
  product/log-service/handler/intelligence.go
Labels: go

#48646 [fix]: [PL-30817]: fix users limit in user group CG
  400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java
  400-rest/src/test/java/software/wings/service/impl/UserGroupServiceImplTest.java
Labels: pl

#48662 fix: [PL-38252]: Fix flaky test
  260-delegate/src/test/java/io/harness/perpetualtask/HttpsPerpetualTaskServiceClientImplTest.java
Labels: pl

#48813 fix: [PL-32498]: Higher Limit for Session Timeout Validation Added
  400-rest/src/test/java/software/wings/service/AccountServiceTest.java
  960-ng-core-beans/src/main/java/io/harness/ng/core/user/SessionTimeoutSettings.java
Labels: pl

#48808 fix: [PL-39128]: Move cg audit fetch query to analytics node
  400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java
Labels: pl

#48935 feat: [PL-27621]: Decommission iterator to remove renewal for root tokens
  120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java
Labels: pl

#48790 fix: [PL-30990]: Removing aclMigrations which was used for migration from NGManager to ACS as part of Access Control Independent service.
  120-ng-manager/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java
  120-ng-manager/src/main/java/io/harness/ng/NextGenPersistenceModule.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/AccessControlMigrationJob.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/AccessControlMigrationModule.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/AccessControlMigrationPersistenceConfig.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/dao/AccessControlMigrationDAO.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/dao/AccessControlMigrationDAOImpl.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/dao/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/models/AccessControlMigration.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/models/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/repositories/AccessControlMigrationRepository.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/repositories/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/AccessControlMigrationService.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/AccessControlMigrationServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/mockserver/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/mockserver/MockRoleAssignment.java
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/resources/BUILD.bazel
  120-ng-manager/src/main/java/io/harness/ng/accesscontrol/resources/MockRoleAssignmentResource.java
  120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java
  120-ng-manager/src/main/java/io/harness/serializer/NextGenRegistrars.java
  120-ng-manager/src/main/java/io/harness/serializer/morphia/MockRoleAssignmentMorphiaRegistrar.java
  120-ng-manager/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrars.java
  120-ng-manager/src/test/java/io/harness/ng/core/event/NGAccountSetupServiceTest.java
  120-ng-manager/src/test/resources/mongo/indexes.txt
Labels: pl

#48987 feat: [PL-39170]: Create default roles assingment in create api for single role binding
  access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java
  access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceTest.java
Labels: pl

#48682 feat: [PL-38908]: Unit tests for Fav utils classes and adding indexes.
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/entities/BUILD.bazel
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/entities/Favorite.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/AccountFavoritesApiImpl.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/OrgFavoritesApiImpl.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/ProjectFavoritesApiImpl.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/FavoritesService.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/utils/FavoritesValidator.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/remote/FavoritesAccountApiImplTest.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/remote/FavoritesOrgApiImplTest.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/remote/FavoritesProjectApiImplTest.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/service/impl/FavoritesServiceImplTest.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/BUILD.bazel
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesResourceUtilsTest.java
  120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesValidatorTest.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl

#48944 fix:[PL-39070]:Added sanitisation of Input Fields for IDP
  122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java
  122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/resources/AuthenticationSettingsResource.java
  122-ng-authentication-settings/src/test/java/io/harness/ng/authenticationsettings/AuthenticationSettingServiceImplTest.java
Labels: pl

#49133 feat: [PL-39408]: allow for creating MockDelegate
  260-delegate/src/main/java/io/harness/delegate/service/common/AbstractDelegateAgentService.java
  260-delegate/src/main/java/io/harness/delegate/service/common/BUILD.bazel
  260-delegate/src/main/java/io/harness/delegate/service/common/SimpleDelegateAgent.java
  260-delegate/src/main/java/io/harness/delegate/service/core/CoreDelegateService.java
  260-delegate/src/main/java/io/harness/delegate/service/core/client/BUILD.bazel
  260-delegate/src/main/java/io/harness/delegate/service/core/client/DelegateCoreManagerClient.java
  260-delegate/src/main/java/io/harness/delegate/service/mock/BUILD.bazel
  260-delegate/src/main/java/io/harness/delegate/service/mock/MockDelegateAgentService.java
Labels: pl

#49362 feat: [PL-39081]: Added a param to include parent scope settings
  120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingConstants.java
  120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java
  120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java
  120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/SettingsService.java
  120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
  120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java
  120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java
  120-ng-manager/src/test/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtilsTest.java
Labels: pl

#48825 fix: [PL-38828]: Added RBAC check to list Connectors when specific selected.
  120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/ConnectorServiceImplTest.java
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/OrgConnectorApiImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/helper/ConnectorRbacHelper.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorStatisticsHelper.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java
  440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorFilterService.java
  440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorService.java
  440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepository.java
  440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/AccountConnectorApiImplTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/ConnectorResourceTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/OrgConnectorApiImplTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/ProjectConnectorApiImplTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/helper/ConnectorRbacHelperTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/ConnectorFilterServiceImplTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/ConnectorListWithFiltersTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/ConnectorStatisticsHelperTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/DefaultConnectorServiceImplTest.java
  954-connector-beans/src/main/java/io/harness/connector/ConnectorFilterPropertiesDTO.java
Labels: pl

#49119 techdebt: [CI-8219]: Add FF SDK support in CI manager
  125-cd-nextgen/src/test/java/io/harness/cdng/CDNGTestRule.java
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java
  332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java
  332-ci-manager/app/src/main/java/io/harness/ci/CIManagerConfiguration.java
  332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java
  332-ci-manager/app/src/test/java/io/harness/app/impl/CIManagerRule.java
  332-ci-manager/build/container/scripts/replace_configs.sh
  332-ci-manager/config/ci-manager-config.yml
  332-ci-manager/container/scripts/replace_configs.sh
  332-ci-manager/service/BUILD.bazel
  879-pipeline-ci-commons/src/main/java/io/harness/ci/ff/impl/CIFeatureFlagServiceImpl.java
  980-commons/src/main/java/io/harness/utils/system/SystemWrapper.java
  dockerization/ci-manager/scripts/replace_configs.sh
Labels: do-not-merge

#49430 [fix]: [PL-39474]: Added leeway of 1 min to Issued At claim
  980-commons/src/main/java/io/harness/security/ServiceTokenGenerator.java
  980-commons/src/test/java/io/harness/security/ServiceTokenGeneratorTest.java
Labels: pl

#49384 [fix]: [CDS-72124]: Fixing nextNode not being set when stepGroup is inside stepGroup and that is child of parallel node
  879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/StepGroupPMSPlanCreatorV2.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlField.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericStepPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/steps/GenericPlanCreatorUtilsTest.java
  clients/pipeline-service/pms-sdk-core/src/test/resources/pipeline-with-stepGroup-inside-stepGroup-parallel.yaml
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep/AbstractContainerStepPlanCreator.java
  pipeline-service/service/src/test/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreatorTest.java
Labels: cds-pl-ready-review

#48990 fix: [CDS-70516]: Fixing reconcilliation flow for remote input sets from BE
  pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java
  pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java
  pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSTest.java
  pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelperTest.java
Labels: cds-pl-ready-review

#49302 [fix]: [CDS-72064]: Old API description change for lastObjectId
  900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityUpdateInfoDTO.java
Labels: cds-pl-ready-review

#49375 fix: [CDS-70676]: pass correct fieldYaml in case of parallel stages or steps
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java
  953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlNodeTest.java
  953-yaml-commons/src/test/resources/stageYaml2.yaml
  pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java
  pipeline-service/modules/orchestration/src/test/java/io/harness/engine/execution/WaitForExecutionInputHelperTest.java
Labels: ready-to-merge, cds-pl-ready-review

#49376 fix: [PL-39304]: Fixed the API documentation of variables to update the type
  120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/dto/StringVariableConfigDTO.java
  120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/dto/VariableConfigDTO.java
Labels: pl

#49397 feat: [PL-39408]: Implement response path for MockDelegate
  260-delegate/src/main/java/io/harness/delegate/service/common/AbstractDelegateAgentService.java
  260-delegate/src/main/java/io/harness/delegate/service/common/SimpleDelegateAgent.java
  260-delegate/src/main/java/io/harness/delegate/service/core/CoreDelegateService.java
  260-delegate/src/main/java/io/harness/delegate/service/core/client/DelegateCoreManagerClient.java
  260-delegate/src/main/java/io/harness/delegate/service/mock/MockDelegateAgentService.java
Labels: pl

#49081 feat: [PL-39076]: Incorporating Favorites Framework on Connectors
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateProjectServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
  120-ng-manager/src/test/java/io/harness/ng/core/api/impl/AggregateProjectServiceImplTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/remote/ProjectResourceTest.java
  440-connector-nextgen/BUILD.bazel
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
  440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java
  440-connector-nextgen/src/test/java/io/harness/connector/ConnectorTestRule.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/ConnectorResourceTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/ConnectorListWithFiltersTest.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/DefaultConnectorServiceImplTest.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/remote/ProjectMapper.java
  950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ProjectService.java
  954-connector-beans/src/main/java/io/harness/connector/ConnectorResponseDTO.java
Labels: pl

#48743 feat: [PL-38977]: Add api to delete all users except the admins
  120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java
  120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java
  120-ng-manager/src/test/java/io/harness/ng/core/event/NGAccountSetupServiceTest.java
  123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java
  123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java
  123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustom.java
  123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustomImpl.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java
  400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
  400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
  400-rest/src/main/java/software/wings/service/intfc/AccountService.java
  953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java
Labels: pl

#49455 fix: [PL-39468]: Added logs for Event listener in Access control service.
  access-control/service/src/main/java/io/harness/accesscontrol/commons/events/EventListener.java
  access-control/service/src/main/java/io/harness/accesscontrol/principals/usergroups/events/UserGroupEventHandler.java
Labels: pl

#49523 feat: [CI-7503]: Add taskID support in SCM
  product/ci/scm/main.go
Labels: go

#48687 feat: [PL-38981]: changes to support migrating users from CG to NG multiple times
  120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java
  120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java
  120-ng-manager/src/test/java/io/harness/ng/core/event/NGAccountSetupServiceTest.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java
  400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java
  400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
  400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
  400-rest/src/main/java/software/wings/service/intfc/AccountService.java
  953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java
Labels: pl

#49388 [fix]: [CDS-72318]: Default key overriding addressed
  953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputsValidator.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java
  953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/RuntimeInputsValidatorTest.java
Labels: cds-pl-ready-review

#49526 fix: [PL-38828]: Fixed pagination to list all connectors. (#49520)
  440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
  440-connector-nextgen/src/test/java/io/harness/connector/apis/resource/ConnectorResourceTest.java
Labels: pl

#49470 feat: [PL-39499]: Evicting favorites when entities are deleted.
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/entities/Favorite.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/FavoritesService.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java
  120-ng-manager/modules/favorites/src/main/java/io/harness/repositories/favorites/spring/FavoriteRepository.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java
  440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
  440-connector-nextgen/src/test/java/io/harness/connector/impl/DefaultConnectorServiceImplTest.java
Labels: pl

#49393 fix: [PL-39440]: Added support to return delegate token value in list api
  120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java
  120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java
  400-rest/src/main/java/io/harness/delegate/resources/DelegateNgTokenInternalResource.java
  400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateNgTokenService.java
  400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
  400-rest/src/test/java/io/harness/service/DelegateNgTokenServiceTest.java
  920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateTokenDetails.java
Labels: pl

#49579 [fix]: [CDS-72124]: Fixing nextNode not being set when stepGroup is inside stepGroup and that is child of parallel node (#49384)
  879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/StepGroupPMSPlanCreatorV2.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlField.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericStepPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/steps/GenericPlanCreatorUtilsTest.java
  clients/pipeline-service/pms-sdk-core/src/test/resources/pipeline-with-stepGroup-inside-stepGroup-parallel.yaml
  pipeline-service/build.properties
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep/AbstractContainerStepPlanCreator.java
  pipeline-service/service/src/test/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreatorTest.java
Labels: cds-pl-ready-review

#49583 [fix]: [CDS-72124]: Fixing nextNode not being set when stepGroup is inside stepGroup and that is child of parallel node (#49384)
  332-ci-manager/build.properties
  879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/StepGroupPMSPlanCreatorV2.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlField.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericStepPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/steps/GenericPlanCreatorUtilsTest.java
  clients/pipeline-service/pms-sdk-core/src/test/resources/pipeline-with-stepGroup-inside-stepGroup-parallel.yaml
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep/AbstractContainerStepPlanCreator.java
  pipeline-service/service/src/test/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreatorTest.java
Labels: cds-pl-ready-review

#49585 [fix]: [CDS-72124]: Fixing nextNode not being set when stepGroup is inside stepGroup and that is child of parallel node (#49384)
  879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/StepGroupPMSPlanCreatorV2.java
  953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlField.java
  build.properties
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericStepPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
  clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/steps/GenericPlanCreatorUtilsTest.java
  clients/pipeline-service/pms-sdk-core/src/test/resources/pipeline-with-stepGroup-inside-stepGroup-parallel.yaml
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep/AbstractContainerStepPlanCreator.java
  pipeline-service/service/src/test/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreatorTest.java
Labels: cds-pl-ready-review

#49327 feat: [PL-39293]: Add manual vault configure to AzurekeyVault
  440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/AzureKeyVaultDTOToEntity.java
  440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/AzureKeyVaultEntityToDTO.java
  440-connector-nextgen/src/test/resources/schema/Connectors/all.json
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/AzureKeyVaultConnectorDTO.java
  954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/outcome/AzureKeyVaultConnectorOutcomeDTO.java
Labels: pl

#48650 feat: [PL-31870]: Changed token list api to return all tokens
  120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java
  120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java
  120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java
  960-ng-core-beans/src/main/java/io/harness/ng/core/dto/TokenFilterDTO.java
Labels: pl

#49731 feat: [PL-39644]: expose env variable for overriding distributed lock config for iacm manager
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
  310-iacm-manager/build/container/scripts/replace_configs.sh
  310-iacm-manager/config/iacm-manager-config.yml
Labels: pl

#49727 feat: [PL-39644]: expose env variable for overriding distributed lock config for verification svc
  270-verification/container/scripts/replace_configs.sh
  270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java
  270-verification/src/main/java/io/harness/app/VerificationServiceConfiguration.java
  270-verification/verification-config.yml
  dockerization/verification/scripts/replace_configs.sh
Labels: pl

#49776 feat: [PL-39691]: Removing FF PL_SIMPLIFY_ACL_CHECK as no longer used.
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl

#49745 fix: [PL-39627]: fix NPE in healthResource
  260-delegate/src/main/java/io/harness/delegate/app/resource/HealthResource.java
  980-commons/src/main/java/io/harness/health/HealthException.java
  debezium-service/service/src/test/java/io/harness/health/HealthResourceImplTest.java
  idp-service/src/test/java/io/harness/idp/health/HealthResourceImplTest.java
  pipeline-service/service/src/test/java/io/harness/pms/health/HealthResourceImplTest.java
Labels: pl

#49735 feat: [PL-38926]: Added More entities to copy script
  scripts/copy-entities/copy_entities_script.py
Labels: pl

#49463 [fix]: [CDS-72312]: Not allowed keywords
  120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java
  970-ng-commons/src/main/java/io/harness/validator/NGVariableNameValidator.java
  980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java
  clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/FilterCreatorHelper.java
Labels: cds-pl-ready-review

#49620 fix: [PL-39609]: fix for not updating project and org identifiers
  120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
  120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java
  120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java
Labels: pl

#49687 feat: [CDS-71973]: Add search support for NG Labels
  953-yaml-commons/src/main/java/io/harness/yaml/core/NGLabel.java
  970-api-services-beans/src/main/java/io/harness/filter/dto/FilterPropertiesDTO.java
  pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java
  pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionFilterPropertiesDTO.java
  pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
Labels: cds-pl-ready-review

#49825 fix: [CDS-71091]: Revert "adding telemetry in template service (#49631)"
  template-service/config/config.yml
  template-service/service/BUILD.bazel
  template-service/service/src/main/java/io/harness/TemplateServiceApplication.java
  template-service/service/src/main/java/io/harness/TemplateServiceConfiguration.java
  template-service/service/src/main/java/io/harness/TemplateServiceModule.java
  template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java
  template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java
  template-service/service/src/test/java/io/harness/template/gitsync/TemplateFullGitSyncHelperTest.java
  template-service/service/src/test/java/io/harness/template/services/NGTemplateServiceHelperTest.java
Labels: gojava

#49817 feat: [CI-7503]: SCM changes to support taskID
  product/ci/scm/grpc/BUILD.bazel
  product/ci/scm/grpc/handler.go
  product/ci/scm/grpc/handler_test.go
  product/ci/scm/grpc/interceptor.go
  product/ci/scm/grpc/server.go
  product/ci/scm/main.go
Labels: go

#49883 fix: [CI-8632]: Update RCA log prompt in log service
  product/log-service/handler/intelligence.go
Labels: go

#49890 [feat]: [CI-8539]: Update ti-service client
  WORKSPACE
Labels: gojava

#49846 feat: [PL-39694]: removed stale FF- SETTING_ATTRIBUTES_SERVICE_ACCOUNT_TOKEN_MIGRATION
  390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java
  390-db-migration/src/main/java/io/harness/migrations/all/SettingAttributesServiceAccountTokenMigration.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: pl

#49715 feat: [CDS-72657]: Adding API to fetch a list of manifest that can be applied as primary
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/OrgServicesApiImpl.java
  120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java
  127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/ManifestType.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java
  127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java
  127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
  127-cd-nextgen-entities/src/test/resources/service/service-with-no-manifests.yaml
  127-cd-nextgen-entities/src/test/resources/service/service-with-primaryManifestRef-Kubernetes.yaml
  127-cd-nextgen-entities/src/test/resources/service/service-with-primaryManifestRef-NativeHelm.yaml
  127-cd-nextgen-entities/src/test/resources/service/service-with-primaryManifestRef-Others.yaml
Labels: gojava

#49865 feat: [PL-39708]: config changes to support redis persistence lock
  270-verification/container/scripts/replace_configs.sh
  270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java
  270-verification/src/main/java/io/harness/app/VerificationServiceConfiguration.java
  270-verification/verification-config.yml
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java
  310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
  310-iacm-manager/build/container/scripts/replace_configs.sh
  310-iacm-manager/config/iacm-manager-config.yml
  ce-nextgen/config/config.yml
  ce-nextgen/service/src/main/java/io/harness/ccm/CENextGenConfiguration.java
  ce-nextgen/service/src/main/java/io/harness/ccm/CENextGenModule.java
  dockerization/ce-nextgen/scripts/replace_configs.sh
  dockerization/template-service/scripts/replace_configs.sh
  template-service/config/config.yml
  template-service/container/scripts/replace_configs.sh
  template-service/service/src/main/java/io/harness/TemplateServiceConfiguration.java
  template-service/service/src/main/java/io/harness/TemplateServiceModule.java
Labels: pl

#49725 fix: [PL-39536]: Reframed user search query in CG
  400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
  400-rest/src/test/java/software/wings/service/impl/UserServiceImplTest.java
Labels: pl

#49178 feat: [PL-39413]: Added support for usage type and usage data in EntityUsageActivityDetail
  120-ng-manager/src/main/java/io/harness/ng/core/entityactivity/mapper/EntityActivityProtoToRestDTOMapper.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/entity/EntityUsageActivityDetail.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/mapper/NGActivityDTOToEntityMapper.java
  950-ng-core/src/main/java/io/harness/ng/core/activityhistory/mapper/NGActivityEntityToDTOMapper.java
  953-events-api/src/main/proto/io/harness/eventsframework/schemas/entityactivity/create_entity_activity.proto
  960-ng-core-beans/src/main/java/io/harness/ng/core/activityhistory/dto/EntityUsageActivityDetailDTO.java
  970-ng-commons/BUILD.bazel
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/BUILD.bazel
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageData.java
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetail.java
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java
  970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageType.java
  970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/BUILD.bazel
  970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_usage_data.proto
  970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_usage_detail.proto
Labels: pl
