Repository harness/harness-core, pull requests merged in 2024-01, with the labels that each got.

#57131 feat: [CDS-82480] Support TrafficRouting for the Canary Step [delegate]
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreator.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryBaseHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryRequestHandlerTest.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionExplanation.java
  970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/Kind.java
Labels: cd-kubernetes, cd-deployments

#57021 techdebt: [CDS-87355]: Remove CDS_CONTAINER_STEP_GROUP FF from code
  360-cg-manager/chart/README.md
  360-cg-manager/chart/values.yaml
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: do-not-merge, cd-deployments, cd-containerStepGroup

#57296 fix: [CI-10916]: backward compatibility for output variable
  product/ci/addon/tasks/run.go
  product/ci/addon/tasks/runtests.go
Labels: go

#57170 [feat]: [CDS-86006]: adding logic for traffic routing step inherit option and…
  260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreator.java
  930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryBaseHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandlerTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/SMITrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactoryTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorTest.java
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit1.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit2.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit3.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit4.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit5.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit6.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/TrafficSplit7.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService1.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService3.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualService4.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceAuthorityRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceHeaderRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceMethodRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServicePortRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceSchemeRule.yaml
  930-delegate-tasks/src/test/resources/k8s/trafficrouting/virtualServiceUriRule.yaml
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
  950-delegate-tasks-beans/src/test/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfigTest.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerService.java
  960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/BUILD.bazel
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/PortMatch.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/istio/VirtualServiceDetailsGsonDeserializer.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/smi/BUILD.bazel
  970-api-services-beans/src/main/java/io/harness/k8s/model/smi/Backend.java
  970-api-services-beans/src/main/java/io/harness/k8s/model/smi/RouteSpecGsonDeserializer.java
Labels: cd-kubernetes, cd-deployments

#57327 feat: [CDS-73091]: sanitized exceptions for ASG delegate handlers
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenDeployCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenPrepareRollbackCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenRollbackCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgCanaryDeleteCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgCanaryDeployCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgPrepareRollbackDataCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingDeployCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingRollbackCommandTaskHandler.java
  930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgShiftTrafficCommandTaskHandler.java
Labels: cd-deployments, cd-asg

#57301 chore: [CDS-87975]: Remove CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS feature flag code usage
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmUtils.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java
  930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSessionConfig.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/winrm/WinRmUtilsTest.java
  930-delegate-tasks/src/test/java/io/harness/delegate/task/winrm/WinRmSessionTest.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskParametersNG.java
  950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinrmTaskParameters.java
  980-commons/src/main/java/io/harness/windows/CmdUtils.java
  980-commons/src/test/java/io/harness/windows/CmdUtilsTest.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java
  pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImplOld.java
Labels: cd-deployments, cd-winrm

#57329 chore: [CDS-86581]: Remove CDS_HELM_FETCH_CHART_METADATA_NG from code
  125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/task/HelmChartManifestTaskHandler.java
  125-cd-nextgen/src/test/java/io/harness/cdng/manifest/steps/task/HelmChartManifestTaskHandlerTest.java
  956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Labels: cd-kubernetes, cd-deployments

#57430 feat: [CDS-87167]: support anonymous github provider in SCM
  952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
  product/ci/scm/gitclient/gitclient.go
  product/ci/scm/proto/scm_service.proto
Labels: cd-deployments

#57209 feat: [PL-43140]: Central certificate management, create certificate API
  120-ng-manager/BUILD.bazel
  120-ng-manager/contracts/openapi/v1/openapi.yaml
  120-ng-manager/modules/ng-certificates/BUILD.bazel
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/entities/NgCertificate.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/mapper/NgCertificateMapper.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/remote/v1/api/AccountCertificateApiImpl.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/remote/v1/api/OrgCertificateApiImpl.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/remote/v1/api/ProjectCertificateApiImpl.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/services/NgCertificateService.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/services/impl/NgCertificateServiceImpl.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/repositories/ngcertificates/spring/NgCertificateRepository.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/serializer/NgCertificateRegistrars.java
  120-ng-manager/modules/ng-certificates/src/main/java/io/harness/serializer/morphia/NgCertificateMorphiaRegistrar.java
  120-ng-manager/modules/ng-certificates/src/test/java/io/harness/ngcertificates/mapper/NgCertificateMapperTest.java
  120-ng-manager/modules/ng-certificates/src/test/java/io/harness/ngcertificates/remote/v1/api/AccountCertificateApiImplTest.java
  120-ng-manager/modules/ng-certificates/src/test/java/io/harness/ngcertificates/remote/v1/api/OrgCertificateApiImplTest.java
  120-ng-manager/modules/ng-certificates/src/test/java/io/harness/ngcertificates/remote/v1/api/ProjectCertificateApiImplTest.java
  120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java
  120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java
  120-ng-manager/src/main/java/io/harness/ng/NgCertificateModule.java
  120-ng-manager/src/main/java/io/harness/serializer/NextGenRegistrars.java
  120-ng-manager/src/test/resources/mongo/indexes.txt
  955-delegate-beans/src/main/java/io/harness/delegate/beans/FileUploadLimit.java
  970-ng-commons/src/main/java/io/harness/errorhandling/BUILD.bazel
  970-ng-commons/src/main/java/io/harness/errorhandling/ErrorMessageUtils.java
  980-commons/src/main/java/io/harness/security/X509Utils.java
Labels: pl
